/*
 JSZip - A Javascript class for generating and reading zip files
<http://stuartk.com/jszip>

(c) 2009-2014 Stuart Knightley <stuart [at] stuartk.com>
Dual licenced under the MIT license or GPLv3. See https://raw.github.com/Stuk/jszip/master/LICENSE.markdown.

JSZip uses the library pako released under the MIT license :
https://github.com/nodeca/pako/blob/master/LICENSE
*/
!function(ca){if("object"==typeof exports&&"undefined"!=typeof module)module.exports=ca();else if("function"==typeof define&&define.amd)define([],ca);else{var v;"undefined"!=typeof window?v=window:"undefined"!=typeof global?v=global:"undefined"!=typeof self&&(v=self);v.JSZip=ca()}}(function(){return function x(v,J,y){function r(w,f){if(!J[w]){if(!v[w]){var t="function"==typeof require&&require;if(!f&&t)return t(w,!0);if(h)return h(w,!0);throw Error("Cannot find module '"+w+"'");}f=J[w]={exports:{}};
v[w][0].call(f.exports,function(k){var l=v[w][1][k];return r(l?l:k)},f,f.exports,x,v,J,y)}return J[w].exports}for(var h="function"==typeof require&&require,A=0;A<y.length;A++)r(y[A]);return r}({1:[function(v,J,y){y.encode=function(x,r){r="";for(var h,A,w,f,t,k,l=0;l<x.length;)h=x.charCodeAt(l++),A=x.charCodeAt(l++),w=x.charCodeAt(l++),f=h>>2,h=(h&3)<<4|A>>4,t=(A&15)<<2|w>>6,k=w&63,isNaN(A)?t=k=64:isNaN(w)&&(k=64),r=r+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(t)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(k);return r};y.decode=function(x,r){r="";var h=0;for(x=x.replace(/[^A-Za-z0-9\+\/=]/g,"");h<x.length;){var A="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(x.charAt(h++));var w="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(x.charAt(h++));var f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(x.charAt(h++));
var t="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(x.charAt(h++));A=A<<2|w>>4;w=(w&15)<<4|f>>2;var k=(f&3)<<6|t;r+=String.fromCharCode(A);64!=f&&(r+=String.fromCharCode(w));64!=t&&(r+=String.fromCharCode(k))}return r}},{}],2:[function(v,J,y){function x(){this.crc32=this.uncompressedSize=this.compressedSize=0;this.compressedContent=this.compressionMethod=null}x.prototype={getContent:function(){return null},getCompressedContent:function(){return null}};J.exports=x},{}],
3:[function(v,J,y){y.STORE={magic:"\x00\x00",compress:function(x,r){return x},uncompress:function(x){return x},compressInputType:null,uncompressInputType:null};y.DEFLATE=v("./flate")},{"./flate":8}],4:[function(v,J,y){var x=v("./utils"),r=[0,1996959894,3993919788,2567524794,124634137,1886057615,3915621685,2657392035,249268274,2044508324,3772115230,2547177864,162941995,2125561021,3887607047,2428444049,498536548,1789927666,4089016648,2227061214,450548861,1843258603,4107580753,2211677639,325883990,1684777152,
4251122042,2321926636,335633487,1661365465,4195302755,2366115317,997073096,1281953886,3579855332,2724688242,1006888145,1258607687,3524101629,2768942443,901097722,1119000684,3686517206,2898065728,853044451,1172266101,3705015759,2882616665,651767980,1373503546,3369554304,3218104598,565507253,1454621731,3485111705,3099436303,671266974,1594198024,3322730930,2970347812,795835527,1483230225,3244367275,3060149565,1994146192,31158534,2563907772,4023717930,1907459465,112637215,2680153253,3904427059,2013776290,
251722036,2517215374,3775830040,2137656763,141376813,2439277719,3865271297,1802195444,476864866,2238001368,4066508878,1812370925,453092731,2181625025,4111451223,1706088902,314042704,2344532202,4240017532,1658658271,366619977,2362670323,4224994405,1303535960,984961486,2747007092,3569037538,1256170817,1037604311,2765210733,3554079995,1131014506,879679996,2909243462,3663771856,1141124467,855842277,2852801631,3708648649,1342533948,654459306,3188396048,3373015174,1466479909,544179635,3110523913,3462522015,
1591671054,702138776,2966460450,3352799412,1504918807,783551873,3082640443,3233442989,3988292384,2596254646,62317068,1957810842,3939845945,2647816111,81470997,1943803523,3814918930,2489596804,225274430,2053790376,3826175755,2466906013,167816743,2097651377,4027552580,2265490386,503444072,1762050814,4150417245,2154129355,426522225,1852507879,4275313526,2312317920,282753626,1742555852,4189708143,2394877945,397917763,1622183637,3604390888,2714866558,953729732,1340076626,3518719985,2797360999,1068828381,
1219638859,3624741850,2936675148,906185462,1090812512,3747672003,2825379669,829329135,1181335161,3412177804,3160834842,628085408,1382605366,3423369109,3138078467,570562233,1426400815,3317316542,2998733608,733239954,1555261956,3268935591,3050360625,752459403,1541320221,2607071920,3965973030,1969922972,40735498,2617837225,3943577151,1913087877,83908371,2512341634,3803740692,2075208622,213261112,2463272603,3855990285,2094854071,198958881,2262029012,4057260610,1759359992,534414190,2176718541,4139329115,
1873836001,414664567,2282248934,4279200368,1711684554,285281116,2405801727,4167216745,1634467795,376229701,2685067896,3608007406,1308918612,956543938,2808555105,3495958263,1231636301,1047427035,2932959818,3654703836,1088359270,936918E3,2847714899,3736837829,1202900863,817233897,3183342108,3401237130,1404277552,615818150,3134207493,3453421203,1423857449,601450431,3009837614,3294710456,1567103746,711928724,3020668471,3272380065,1510334235,755167117];J.exports=function(h,A){if("undefined"===typeof h||
!h.length)return 0;var w="string"!==x.getTypeOf(h);"undefined"==typeof A&&(A=0);A^=-1;for(var f=0,t=h.length;f<t;f++){var k=w?h[f]:h.charCodeAt(f);k=(A^k)&255;k=r[k];A=A>>>8^k}return A^-1}},{"./utils":21}],5:[function(v,J,y){function x(h){this.data=null;this.index=this.length=0}var r=v("./utils");x.prototype={checkOffset:function(h){this.checkIndex(this.index+h)},checkIndex:function(h){if(this.length<h||0>h)throw Error("End of data reached (data length = "+this.length+", asked index = "+h+"). Corrupted zip ?");
},setIndex:function(h){this.checkIndex(h);this.index=h},skip:function(h){this.setIndex(this.index+h)},byteAt:function(h){},readInt:function(h){var A=0,w;this.checkOffset(h);for(w=this.index+h-1;w>=this.index;w--)A=(A<<8)+this.byteAt(w);this.index+=h;return A},readString:function(h){return r.transformTo("string",this.readData(h))},readData:function(h){},lastIndexOfSignature:function(h){},readDate:function(){var h=this.readInt(4);return new Date((h>>25&127)+1980,(h>>21&15)-1,h>>16&31,h>>11&31,h>>5&
63,(h&31)<<1)}};J.exports=x},{"./utils":21}],6:[function(v,J,y){y.base64=!1;y.binary=!1;y.dir=!1;y.createFolders=!1;y.date=null;y.compression=null;y.compressionOptions=null;y.comment=null;y.unixPermissions=null;y.dosPermissions=null},{}],7:[function(v,J,y){var x=v("./utils");y.string2binary=function(r){return x.string2binary(r)};y.string2Uint8Array=function(r){return x.transformTo("uint8array",r)};y.uint8Array2String=function(r){return x.transformTo("string",r)};y.string2Blob=function(r){r=x.transformTo("arraybuffer",
r);return x.arrayBuffer2Blob(r)};y.arrayBuffer2Blob=function(r){return x.arrayBuffer2Blob(r)};y.transformTo=function(r,h){return x.transformTo(r,h)};y.getTypeOf=function(r){return x.getTypeOf(r)};y.checkSupport=function(r){return x.checkSupport(r)};y.MAX_VALUE_16BITS=x.MAX_VALUE_16BITS;y.MAX_VALUE_32BITS=x.MAX_VALUE_32BITS;y.pretty=function(r){return x.pretty(r)};y.findCompression=function(r){return x.findCompression(r)};y.isRegExp=function(r){return x.isRegExp(r)}},{"./utils":21}],8:[function(v,
J,y){J="undefined"!==typeof Uint8Array&&"undefined"!==typeof Uint16Array&&"undefined"!==typeof Uint32Array;var x=v("pako");y.uncompressInputType=J?"uint8array":"array";y.compressInputType=J?"uint8array":"array";y.magic="\b\x00";y.compress=function(r,h){return x.deflateRaw(r,{level:h.level||-1})};y.uncompress=function(r){return x.inflateRaw(r)}},{pako:24}],9:[function(v,J,y){function x(h,A){if(!(this instanceof x))return new x(h,A);this.files={};this.comment=null;this.root="";h&&this.load(h,A);this.clone=
function(){var w=new x,f;for(f in this)"function"!==typeof this[f]&&(w[f]=this[f]);return w}}var r=v("./base64");x.prototype=v("./object");x.prototype.load=v("./load");x.support=v("./support");x.defaults=v("./defaults");x.utils=v("./deprecatedPublicUtils");x.base64={encode:function(h){return r.encode(h)},decode:function(h){return r.decode(h)}};x.compressions=v("./compressions");J.exports=x},{"./base64":1,"./compressions":3,"./defaults":6,"./deprecatedPublicUtils":7,"./load":10,"./object":13,"./support":17}],
10:[function(v,J,y){var x=v("./base64"),r=v("./zipEntries");J.exports=function(h,A){var w;A=A||{};A.base64&&(h=x.decode(h));var f=new r(h,A);h=f.files;for(w=0;w<h.length;w++){var t=h[w];this.file(t.fileName,t.decompressed,{binary:!0,optimizedBinaryString:!0,date:t.date,dir:t.dir,comment:t.fileComment.length?t.fileComment:null,unixPermissions:t.unixPermissions,dosPermissions:t.dosPermissions,createFolders:A.createFolders})}f.zipComment.length&&(this.comment=f.zipComment);return this}},{"./base64":1,
"./zipEntries":22}],11:[function(v,J,y){(function(x){J.exports=function(r,h){return new x(r,h)};J.exports.test=function(r){return x.isBuffer(r)}}).call(this,"undefined"!==typeof Buffer?Buffer:void 0)},{}],12:[function(v,J,y){function x(r){this.data=r;this.length=this.data.length;this.index=0}v=v("./uint8ArrayReader");x.prototype=new v;x.prototype.readData=function(r){this.checkOffset(r);var h=this.data.slice(this.index,this.index+r);this.index+=r;return h};J.exports=x},{"./uint8ArrayReader":18}],
13:[function(v,J,y){var x=v("./support"),r=v("./utils"),h=v("./crc32"),A=v("./signature"),w=v("./defaults"),f=v("./base64"),t=v("./compressions"),k=v("./compressedObject"),l=v("./nodeBuffer"),p=v("./utf8"),n=v("./stringWriter"),G=v("./uint8ArrayWriter"),O=function(a){if(a._data instanceof k&&(a._data=a._data.getContent(),a.options.binary=!0,a.options.base64=!1,"uint8array"===r.getTypeOf(a._data))){var e=a._data;a._data=new Uint8Array(e.length);0!==e.length&&a._data.set(e,0)}return a._data},T=function(a){var e=
O(a);return"string"===r.getTypeOf(e)?!a.options.binary&&x.nodebuffer?l(e,"utf-8"):a.asBinary():e},u=function(a){var e=O(this);if(null===e||"undefined"===typeof e)return"";this.options.base64&&(e=f.decode(e));e=a&&this.options.binary?F.utf8decode(e):r.transformTo("string",e);a||this.options.binary||(e=r.transformTo("string",F.utf8encode(e)));return e},D=function(a,e,b){this.name=a;this.dir=b.dir;this.date=b.date;this.comment=b.comment;this.unixPermissions=b.unixPermissions;this.dosPermissions=b.dosPermissions;
this._data=e;this.options=b;this._initialMetadata={dir:b.dir,date:b.date}};D.prototype={asText:function(){return u.call(this,!0)},asBinary:function(){return u.call(this,!1)},asNodeBuffer:function(){var a=T(this);return r.transformTo("nodebuffer",a)},asUint8Array:function(){var a=T(this);return r.transformTo("uint8array",a)},asArrayBuffer:function(){return this.asUint8Array().buffer}};var L=function(a,e){var b="",m;for(m=0;m<e;m++)b+=String.fromCharCode(a&255),a>>>=8;return b},N=function(){var a={},
e,b;for(e=0;e<arguments.length;e++)for(b in arguments[e])arguments[e].hasOwnProperty(b)&&"undefined"===typeof a[b]&&(a[b]=arguments[e][b]);return a},W=function(a,e,b){var m=r.getTypeOf(e);b=b||{};!0!==b.base64||null!==b.binary&&void 0!==b.binary||(b.binary=!0);b=N(b,w);b.date=b.date||new Date;null!==b.compression&&(b.compression=b.compression.toUpperCase());"string"===typeof b.unixPermissions&&(b.unixPermissions=parseInt(b.unixPermissions,8));b.unixPermissions&&b.unixPermissions&16384&&(b.dir=!0);
b.dosPermissions&&b.dosPermissions&16&&(b.dir=!0);b.dir&&(a=c(a));var g;if(g=b.createFolders){var q=a;"/"==q.slice(-1)&&(q=q.substring(0,q.length-1));g=q.lastIndexOf("/");g=q=0<g?q.substring(0,g):""}g&&P.call(this,q,!0);if(b.dir||null===e||"undefined"===typeof e)b.base64=!1,b.binary=!1,e=null;else if("string"===m)b.binary&&!b.base64&&!0!==b.optimizedBinaryString&&(e=r.string2binary(e));else{b.base64=!1;b.binary=!0;if(!(m||e instanceof k))throw Error("The data of '"+a+"' is in an unsupported format !");
"arraybuffer"===m&&(e=r.transformTo("uint8array",e))}e=new D(a,e,b);return this.files[a]=e},c=function(a){"/"!=a.slice(-1)&&(a+="/");return a},P=function(a,e){e="undefined"!==typeof e?e:!1;a=c(a);this.files[a]||W.call(this,a,null,{dir:!0,createFolders:e});return this.files[a]},F={load:function(a,e){throw Error("Load method is not defined. Is the file jszip-load.js included ?");},filter:function(a){var e=[],b;for(b in this.files)if(this.files.hasOwnProperty(b)){var m=this.files[b];var g=new D(m.name,
m._data,N(m.options));m=b.slice(this.root.length,b.length);b.slice(0,this.root.length)===this.root&&a(m,g)&&e.push(g)}return e},file:function(a,e,b){if(1===arguments.length){if(r.isRegExp(a)){var m=a;return this.filter(function(g,q){return!q.dir&&m.test(g)})}return this.filter(function(g,q){return!q.dir&&g===a})[0]||null}a=this.root+a;W.call(this,a,e,b);return this},folder:function(a){if(!a)return this;if(r.isRegExp(a))return this.filter(function(m,g){return g.dir&&a.test(m)});var e=P.call(this,this.root+
a),b=this.clone();b.root=e.name;return b},remove:function(a){a=this.root+a;var e=this.files[a];e||("/"!=a.slice(-1)&&(a+="/"),e=this.files[a]);if(e&&!e.dir)delete this.files[a];else{e=this.filter(function(m,g){return g.name.slice(0,a.length)===a});for(var b=0;b<e.length;b++)delete this.files[e[b].name]}return this},generate:function(a){a=N(a||{},{base64:!0,compression:"STORE",compressionOptions:null,type:"base64",platform:"DOS",comment:null,mimeType:"application/zip"});r.checkSupport(a.type);if("darwin"===
a.platform||"freebsd"===a.platform||"linux"===a.platform||"sunos"===a.platform)a.platform="UNIX";"win32"===a.platform&&(a.platform="DOS");var e=[],b=0,m=0,g=r.transformTo("string",this.utf8encode(a.comment||this.comment||""));for(U in this.files)if(this.files.hasOwnProperty(U)){var q=this.files[U],S=q.options.compression||a.compression.toUpperCase(),E=t[S];if(!E)throw Error(S+" is not a valid compression method !");S=q;var R=E,H=q.options.compressionOptions||a.compressionOptions||{},B=new k;if(S._data instanceof
k)B.uncompressedSize=S._data.uncompressedSize,B.crc32=S._data.crc32,0===B.uncompressedSize||S.dir?(R=t.STORE,B.compressedContent="",B.crc32=0):S._data.compressionMethod===R.magic?B.compressedContent=S._data.getCompressedContent():(E=S._data.getContent(),B.compressedContent=R.compress(r.transformTo(R.compressInputType,E),H));else{E=T(S);if(!E||0===E.length||S.dir)R=t.STORE,E="";B.uncompressedSize=E.length;B.crc32=h(E);B.compressedContent=R.compress(r.transformTo(R.compressInputType,E),H)}B.compressedSize=
B.compressedContent.length;B.compressionMethod=R.magic;S=B;var d=q;q=S;E=b;var z=a.platform;if(option.manga_sjis){H=d.name;B=[];var C=H.length;for(R=0;R<C;R++)B.push(H.charCodeAt(R));R=Encoding.convert(B,"SJIS","UNICODE");R=Encoding.codeToString(R);d.name=R}else R=p.utf8encode(d.name);R=r.transformTo("string",R);B=d.comment||"";H=r.transformTo("string",p.utf8encode(B));C=R.length!==d.name.length;var I=H.length!==B.length,M=d.options;B="";var Q=d._initialMetadata.dir!==d.dir?d.dir:M.dir;var K=d._initialMetadata.date!==
d.date?d.date:M.date;M=0;Q&&(M|=16);if("UNIX"===z){z=798;var V=d=d.unixPermissions;d||(V=Q?16893:33204);M|=(V&65535)<<16}else z=20,M|=(d.dosPermissions||0)&63;Q=K.getHours();Q=Q<<6|K.getMinutes();Q=Q<<5|K.getSeconds()/2;d=K.getFullYear()-1980;d=d<<4|K.getMonth()+1;d=d<<5|K.getDate();C&&(K=L(1,1)+L(h(R),4)+R,B+="up"+L(K.length,2)+K);I&&(K=L(1,1)+L(this.crc32(H),4)+H,B+="uc"+L(K.length,2)+K);C="\n\x00"+(C||I?"\x00\b":"\x00\x00")+q.compressionMethod;C+=L(Q,2);C+=L(d,2);C+=L(q.crc32,4);C+=L(q.compressedSize,
4);C+=L(q.uncompressedSize,4);C+=L(R.length,2);C+=L(B.length,2);d=A.LOCAL_FILE_HEADER+C+R+B;E=A.CENTRAL_FILE_HEADER+L(z,2)+C+L(H.length,2)+"\x00\x00\x00\x00"+L(M,4)+L(E,4)+R+B+H;q={fileRecord:d,dirRecord:E,compressedObject:q};b+=q.fileRecord.length+S.compressedSize;m+=q.dirRecord.length;e.push(q)}g=A.CENTRAL_DIRECTORY_END+"\x00\x00\x00\x00"+L(e.length,2)+L(e.length,2)+L(m,4)+L(b,4)+L(g.length,2)+g;var U=a.type.toLowerCase();b="uint8array"===U||"arraybuffer"===U||"blob"===U||"nodebuffer"===U?new G(b+
m+g.length):new n(b+m+g.length);for(m=0;m<e.length;m++)b.append(e[m].fileRecord),b.append(e[m].compressedObject.compressedContent);for(m=0;m<e.length;m++)b.append(e[m].dirRecord);b.append(g);e=b.finalize();switch(a.type.toLowerCase()){case "uint8array":case "arraybuffer":case "nodebuffer":return r.transformTo(a.type.toLowerCase(),e);case "blob":return r.arrayBuffer2Blob(r.transformTo("arraybuffer",e),a.mimeType);case "base64":return a.base64?f.encode(e):e;default:return e}},crc32:function(a,e){return h(a,
e)},utf8encode:function(a){return r.transformTo("string",p.utf8encode(a))},utf8decode:function(a){return p.utf8decode(a)}};J.exports=F},{"./base64":1,"./compressedObject":2,"./compressions":3,"./crc32":4,"./defaults":6,"./nodeBuffer":11,"./signature":14,"./stringWriter":16,"./support":17,"./uint8ArrayWriter":19,"./utf8":20,"./utils":21}],14:[function(v,J,y){y.LOCAL_FILE_HEADER="PK\u0003\u0004";y.CENTRAL_FILE_HEADER="PK\u0001\u0002";y.CENTRAL_DIRECTORY_END="PK\u0005\u0006";y.ZIP64_CENTRAL_DIRECTORY_LOCATOR=
"PK\u0006\u0007";y.ZIP64_CENTRAL_DIRECTORY_END="PK\u0006\u0006";y.DATA_DESCRIPTOR="PK\u0007\b"},{}],15:[function(v,J,y){function x(h,A){this.data=h;A||(this.data=r.string2binary(this.data));this.length=this.data.length;this.index=0}y=v("./dataReader");var r=v("./utils");x.prototype=new y;x.prototype.byteAt=function(h){return this.data.charCodeAt(h)};x.prototype.lastIndexOfSignature=function(h){return this.data.lastIndexOf(h)};x.prototype.readData=function(h){this.checkOffset(h);var A=this.data.slice(this.index,
this.index+h);this.index+=h;return A};J.exports=x},{"./dataReader":5,"./utils":21}],16:[function(v,J,y){var x=v("./utils");v=function(){this.data=[]};v.prototype={append:function(r){r=x.transformTo("string",r);this.data.push(r)},finalize:function(){return this.data.join("")}};J.exports=v},{"./utils":21}],17:[function(v,J,y){v="undefined"!==typeof Buffer?Buffer:void 0;y.base64=!0;y.array=!0;y.string=!0;y.arraybuffer="undefined"!==typeof ArrayBuffer&&"undefined"!==typeof Uint8Array;y.nodebuffer="undefined"!==
typeof v;y.uint8array="undefined"!==typeof Uint8Array;if("undefined"===typeof ArrayBuffer)y.blob=!1;else{v=new ArrayBuffer(0);try{y.blob=0===(new Blob([v],{type:"application/zip"})).size}catch(r){try{var x=new (window.BlobBuilder||window.WebKitBlobBuilder||window.MozBlobBuilder||window.MSBlobBuilder);x.append(v);y.blob=0===x.getBlob("application/zip").size}catch(h){y.blob=!1}}}},{}],18:[function(v,J,y){function x(r){r&&(this.data=r,this.length=this.data.length,this.index=0)}v=v("./dataReader");x.prototype=
new v;x.prototype.byteAt=function(r){return this.data[r]};x.prototype.lastIndexOfSignature=function(r){var h=r.charCodeAt(0),A=r.charCodeAt(1),w=r.charCodeAt(2);r=r.charCodeAt(3);for(var f=this.length-4;0<=f;--f)if(this.data[f]===h&&this.data[f+1]===A&&this.data[f+2]===w&&this.data[f+3]===r)return f;return-1};x.prototype.readData=function(r){this.checkOffset(r);if(0===r)return new Uint8Array(0);var h=this.data.subarray(this.index,this.index+r);this.index+=r;return h};J.exports=x},{"./dataReader":5}],
19:[function(v,J,y){var x=v("./utils");v=function(r){this.data=new Uint8Array(r);this.index=0};v.prototype={append:function(r){0!==r.length&&(r=x.transformTo("uint8array",r),this.data.set(r,this.index),this.index+=r.length)},finalize:function(){return this.data}};J.exports=v},{"./utils":21}],20:[function(v,J,y){var x=v("./utils"),r=v("./support"),h=v("./nodeBuffer"),A=Array(256);for(v=0;256>v;v++)A[v]=252<=v?6:248<=v?5:240<=v?4:224<=v?3:192<=v?2:1;A[254]=A[254]=1;var w=function(f){var t,k,l=f.length,
p=Array(2*l);for(t=k=0;t<l;){var n=f[t++];if(128>n)p[k++]=n;else{var G=A[n];if(4<G)p[k++]=65533,t+=G-1;else{for(n&=2===G?31:3===G?15:7;1<G&&t<l;)n=n<<6|f[t++]&63,G--;1<G?p[k++]=65533:65536>n?p[k++]=n:(n-=65536,p[k++]=55296|n>>10&1023,p[k++]=56320|n&1023)}}}p.length!==k&&(p.subarray?p=p.subarray(0,k):p.length=k);return x.applyFromCharCode(p)};y.utf8encode=function(f){if(r.nodebuffer)return h(f,"utf-8");var t,k,l=f.length,p=0;for(t=0;t<l;t++){var n=f.charCodeAt(t);if(55296===(n&64512)&&t+1<l){var G=
f.charCodeAt(t+1);56320===(G&64512)&&(n=65536+(n-55296<<10)+(G-56320),t++)}p+=128>n?1:2048>n?2:65536>n?3:4}var O=r.uint8array?new Uint8Array(p):Array(p);for(t=k=0;k<p;t++)n=f.charCodeAt(t),55296===(n&64512)&&t+1<l&&(G=f.charCodeAt(t+1),56320===(G&64512)&&(n=65536+(n-55296<<10)+(G-56320),t++)),128>n?O[k++]=n:(2048>n?O[k++]=192|n>>>6:(65536>n?O[k++]=224|n>>>12:(O[k++]=240|n>>>18,O[k++]=128|n>>>12&63),O[k++]=128|n>>>6&63),O[k++]=128|n&63);return O};y.utf8decode=function(f){if(r.nodebuffer)return x.transformTo("nodebuffer",
f).toString("utf-8");f=x.transformTo(r.uint8array?"uint8array":"array",f);for(var t=[],k=0,l=f.length;k<l;){var p;var n=Math.min(k+65536,l);n=n||f.length;n>f.length&&(n=f.length);for(p=n-1;0<=p&&128===(f[p]&192);)p--;p=0>p?n:0===p?n:p+A[f[p]]>n?p:n;r.uint8array?t.push(w(f.subarray(k,p))):t.push(w(f.slice(k,p)));k=p}return t.join("")}},{"./nodeBuffer":11,"./support":17,"./utils":21}],21:[function(v,J,y){function x(l){return l}function r(l,p){for(var n=0;n<l.length;++n)p[n]=l.charCodeAt(n)&255;return p}
function h(l){var p=65536,n=[],G=l.length,O=y.getTypeOf(l),T=0,u=!0;try{switch(O){case "uint8array":String.fromCharCode.apply(null,new Uint8Array(0));break;case "nodebuffer":String.fromCharCode.apply(null,t(0))}}catch(D){u=!1}if(!u){p="";for(n=0;n<l.length;n++)p+=String.fromCharCode(l[n]);return p}for(;T<G&&1<p;)try{"array"===O||"nodebuffer"===O?n.push(String.fromCharCode.apply(null,l.slice(T,Math.min(T+p,G)))):n.push(String.fromCharCode.apply(null,l.subarray(T,Math.min(T+p,G)))),T+=p}catch(D){p=
Math.floor(p/2)}return n.join("")}function A(l,p){for(var n=0;n<l.length;n++)p[n]=l[n];return p}var w=v("./support"),f=v("./compressions"),t=v("./nodeBuffer");y.string2binary=function(l){for(var p="",n=0;n<l.length;n++)p+=String.fromCharCode(l.charCodeAt(n)&255);return p};y.arrayBuffer2Blob=function(l,p){y.checkSupport("blob");p=p||"application/zip";try{return new Blob([l],{type:p})}catch(G){try{var n=new (window.BlobBuilder||window.WebKitBlobBuilder||window.MozBlobBuilder||window.MSBlobBuilder);
n.append(l);return n.getBlob(p)}catch(O){throw Error("Bug : can't construct the Blob.");}}};y.applyFromCharCode=h;var k={};k.string={string:x,array:function(l){return r(l,Array(l.length))},arraybuffer:function(l){return k.string.uint8array(l).buffer},uint8array:function(l){return r(l,new Uint8Array(l.length))},nodebuffer:function(l){return r(l,t(l.length))}};k.array={string:h,array:x,arraybuffer:function(l){return(new Uint8Array(l)).buffer},uint8array:function(l){return new Uint8Array(l)},nodebuffer:function(l){return t(l)}};
k.arraybuffer={string:function(l){return h(new Uint8Array(l))},array:function(l){return A(new Uint8Array(l),Array(l.byteLength))},arraybuffer:x,uint8array:function(l){return new Uint8Array(l)},nodebuffer:function(l){return t(new Uint8Array(l))}};k.uint8array={string:h,array:function(l){return A(l,Array(l.length))},arraybuffer:function(l){return l.buffer},uint8array:x,nodebuffer:function(l){return t(l)}};k.nodebuffer={string:h,array:function(l){return A(l,Array(l.length))},arraybuffer:function(l){return k.nodebuffer.uint8array(l).buffer},
uint8array:function(l){return A(l,new Uint8Array(l.length))},nodebuffer:x};y.transformTo=function(l,p){p||="";if(!l)return p;y.checkSupport(l);var n=y.getTypeOf(p);return k[n][l](p)};y.getTypeOf=function(l){if("string"===typeof l)return"string";if("[object Array]"===Object.prototype.toString.call(l))return"array";if(w.nodebuffer&&t.test(l))return"nodebuffer";if(w.uint8array&&l instanceof Uint8Array)return"uint8array";if(w.arraybuffer&&l instanceof ArrayBuffer)return"arraybuffer"};y.checkSupport=function(l){if(!w[l.toLowerCase()])throw Error(l+
" is not supported by this browser");};y.MAX_VALUE_16BITS=65535;y.MAX_VALUE_32BITS=-1;y.pretty=function(l){var p="",n;for(n=0;n<(l||"").length;n++){var G=l.charCodeAt(n);p+="\\x"+(16>G?"0":"")+G.toString(16).toUpperCase()}return p};y.findCompression=function(l){for(var p in f)if(f.hasOwnProperty(p)&&f[p].magic===l)return f[p];return null};y.isRegExp=function(l){return"[object RegExp]"===Object.prototype.toString.call(l)}},{"./compressions":3,"./nodeBuffer":11,"./support":17}],22:[function(v,J,y){function x(p,
n){this.files=[];this.loadOptions=n;p&&this.load(p)}var r=v("./stringReader"),h=v("./nodeBufferReader"),A=v("./uint8ArrayReader"),w=v("./utils"),f=v("./signature"),t=v("./zipEntry"),k=v("./support"),l=v("./object");x.prototype={checkSignature:function(p){var n=this.reader.readString(4);if(n!==p)throw Error("Corrupted zip or bug : unexpected signature ("+w.pretty(n)+", expected "+w.pretty(p)+")");},readBlockEndOfCentral:function(){this.diskNumber=this.reader.readInt(2);this.diskWithCentralDirStart=
this.reader.readInt(2);this.centralDirRecordsOnThisDisk=this.reader.readInt(2);this.centralDirRecords=this.reader.readInt(2);this.centralDirSize=this.reader.readInt(4);this.centralDirOffset=this.reader.readInt(4);this.zipCommentLength=this.reader.readInt(2);this.zipComment=this.reader.readString(this.zipCommentLength);this.zipComment=l.utf8decode(this.zipComment)},readBlockZip64EndOfCentral:function(){this.zip64EndOfCentralSize=this.reader.readInt(8);this.versionMadeBy=this.reader.readString(2);this.versionNeeded=
this.reader.readInt(2);this.diskNumber=this.reader.readInt(4);this.diskWithCentralDirStart=this.reader.readInt(4);this.centralDirRecordsOnThisDisk=this.reader.readInt(8);this.centralDirRecords=this.reader.readInt(8);this.centralDirSize=this.reader.readInt(8);this.centralDirOffset=this.reader.readInt(8);this.zip64ExtensibleData={};for(var p=this.zip64EndOfCentralSize-44,n,G,O;0<p;)n=this.reader.readInt(2),G=this.reader.readInt(4),O=this.reader.readString(G),this.zip64ExtensibleData[n]={id:n,length:G,
value:O}},readBlockZip64EndOfCentralLocator:function(){this.diskWithZip64CentralDirStart=this.reader.readInt(4);this.relativeOffsetEndOfZip64CentralDir=this.reader.readInt(8);this.disksCount=this.reader.readInt(4);if(1<this.disksCount)throw Error("Multi-volumes zip are not supported");},readLocalFiles:function(){var p;for(p=0;p<this.files.length;p++){var n=this.files[p];this.reader.setIndex(n.localHeaderOffset);this.checkSignature(f.LOCAL_FILE_HEADER);n.readLocalPart(this.reader);n.handleUTF8();n.processAttributes()}},
readCentralDir:function(){for(this.reader.setIndex(this.centralDirOffset);this.reader.readString(4)===f.CENTRAL_FILE_HEADER;){var p=new t({zip64:this.zip64},this.loadOptions);p.readCentralPart(this.reader);this.files.push(p)}},readEndOfCentral:function(){var p=this.reader.lastIndexOfSignature(f.CENTRAL_DIRECTORY_END);if(-1===p){p=!0;try{this.reader.setIndex(0),this.checkSignature(f.LOCAL_FILE_HEADER),p=!1}catch(n){}if(p)throw Error("Can't find end of central directory : is this a zip file ? If it is, see http://stuk.github.io/jszip/documentation/howto/read_zip.html");
throw Error("Corrupted zip : can't find end of central directory");}this.reader.setIndex(p);this.checkSignature(f.CENTRAL_DIRECTORY_END);this.readBlockEndOfCentral();if(this.diskNumber===w.MAX_VALUE_16BITS||this.diskWithCentralDirStart===w.MAX_VALUE_16BITS||this.centralDirRecordsOnThisDisk===w.MAX_VALUE_16BITS||this.centralDirRecords===w.MAX_VALUE_16BITS||this.centralDirSize===w.MAX_VALUE_32BITS||this.centralDirOffset===w.MAX_VALUE_32BITS){this.zip64=!0;p=this.reader.lastIndexOfSignature(f.ZIP64_CENTRAL_DIRECTORY_LOCATOR);
if(-1===p)throw Error("Corrupted zip : can't find the ZIP64 end of central directory locator");this.reader.setIndex(p);this.checkSignature(f.ZIP64_CENTRAL_DIRECTORY_LOCATOR);this.readBlockZip64EndOfCentralLocator();this.reader.setIndex(this.relativeOffsetEndOfZip64CentralDir);this.checkSignature(f.ZIP64_CENTRAL_DIRECTORY_END);this.readBlockZip64EndOfCentral()}},prepareReader:function(p){var n=w.getTypeOf(p);this.reader="string"!==n||k.uint8array?"nodebuffer"===n?new h(p):new A(w.transformTo("uint8array",
p)):new r(p,this.loadOptions.optimizedBinaryString)},load:function(p){this.prepareReader(p);this.readEndOfCentral();this.readCentralDir();this.readLocalFiles()}};J.exports=x},{"./nodeBufferReader":12,"./object":13,"./signature":14,"./stringReader":15,"./support":17,"./uint8ArrayReader":18,"./utils":21,"./zipEntry":23}],23:[function(v,J,y){function x(f,t){this.options=f;this.loadOptions=t}var r=v("./stringReader"),h=v("./utils"),A=v("./compressedObject"),w=v("./object");x.prototype={isEncrypted:function(){return 1===
(this.bitFlag&1)},useUTF8:function(){return 2048===(this.bitFlag&2048)},prepareCompressedContent:function(f,t,k){return function(){var l=f.index;f.setIndex(t);var p=f.readData(k);f.setIndex(l);return p}},prepareContent:function(f,t,k,l,p){return function(){var n=h.transformTo(l.uncompressInputType,this.getCompressedContent());n=l.uncompress(n);if(n.length!==p)throw Error("Bug : uncompressed data size mismatch");return n}},readLocalPart:function(f){f.skip(22);this.fileNameLength=f.readInt(2);var t=
f.readInt(2);this.fileName=f.readString(this.fileNameLength);f.skip(t);if(-1==this.compressedSize||-1==this.uncompressedSize)throw Error("Bug or corrupted zip : didn't get enough informations from the central directory (compressedSize == -1 || uncompressedSize == -1)");t=h.findCompression(this.compressionMethod);if(null===t)throw Error("Corrupted zip : compression "+h.pretty(this.compressionMethod)+" unknown (inner file : "+this.fileName+")");this.decompressed=new A;this.decompressed.compressedSize=
this.compressedSize;this.decompressed.uncompressedSize=this.uncompressedSize;this.decompressed.crc32=this.crc32;this.decompressed.compressionMethod=this.compressionMethod;this.decompressed.getCompressedContent=this.prepareCompressedContent(f,f.index,this.compressedSize,t);this.decompressed.getContent=this.prepareContent(f,f.index,this.compressedSize,t,this.uncompressedSize);if(this.loadOptions.checkCRC32&&(this.decompressed=h.transformTo("string",this.decompressed.getContent()),w.crc32(this.decompressed)!==
this.crc32))throw Error("Corrupted zip : CRC32 mismatch");},readCentralPart:function(f){this.versionMadeBy=f.readInt(2);this.versionNeeded=f.readInt(2);this.bitFlag=f.readInt(2);this.compressionMethod=f.readString(2);this.date=f.readDate();this.crc32=f.readInt(4);this.compressedSize=f.readInt(4);this.uncompressedSize=f.readInt(4);this.fileNameLength=f.readInt(2);this.extraFieldsLength=f.readInt(2);this.fileCommentLength=f.readInt(2);this.diskNumberStart=f.readInt(2);this.internalFileAttributes=f.readInt(2);
this.externalFileAttributes=f.readInt(4);this.localHeaderOffset=f.readInt(4);if(this.isEncrypted())throw Error("Encrypted zip are not supported");this.fileName=f.readString(this.fileNameLength);this.readExtraFields(f);this.parseZIP64ExtraField(f);this.fileComment=f.readString(this.fileCommentLength)},processAttributes:function(){this.dosPermissions=this.unixPermissions=null;var f=this.versionMadeBy>>8;this.dir=this.externalFileAttributes&16?!0:!1;0===f&&(this.dosPermissions=this.externalFileAttributes&
63);3===f&&(this.unixPermissions=this.externalFileAttributes>>16&65535);this.dir||"/"!==this.fileName.slice(-1)||(this.dir=!0)},parseZIP64ExtraField:function(f){this.extraFields[1]&&(f=new r(this.extraFields[1].value),this.uncompressedSize===h.MAX_VALUE_32BITS&&(this.uncompressedSize=f.readInt(8)),this.compressedSize===h.MAX_VALUE_32BITS&&(this.compressedSize=f.readInt(8)),this.localHeaderOffset===h.MAX_VALUE_32BITS&&(this.localHeaderOffset=f.readInt(8)),this.diskNumberStart===h.MAX_VALUE_32BITS&&
(this.diskNumberStart=f.readInt(4)))},readExtraFields:function(f){var t=f.index;for(this.extraFields=this.extraFields||{};f.index<t+this.extraFieldsLength;){var k=f.readInt(2);var l=f.readInt(2);var p=f.readString(l);this.extraFields[k]={id:k,length:l,value:p}}},handleUTF8:function(){if(this.useUTF8())this.fileName=w.utf8decode(this.fileName),this.fileComment=w.utf8decode(this.fileComment);else{var f=this.findExtraFieldUnicodePath();null!==f&&(this.fileName=f);f=this.findExtraFieldUnicodeComment();
null!==f&&(this.fileComment=f)}},findExtraFieldUnicodePath:function(){var f=this.extraFields[28789];if(f){var t=new r(f.value);return 1!==t.readInt(1)||w.crc32(this.fileName)!==t.readInt(4)?null:w.utf8decode(t.readString(f.length-5))}return null},findExtraFieldUnicodeComment:function(){var f=this.extraFields[25461];if(f){var t=new r(f.value);return 1!==t.readInt(1)||w.crc32(this.fileComment)!==t.readInt(4)?null:w.utf8decode(t.readString(f.length-5))}return null}};J.exports=x},{"./compressedObject":2,
"./object":13,"./stringReader":15,"./utils":21}],24:[function(v,J,y){y=v("./lib/utils/common").assign;var x=v("./lib/deflate"),r=v("./lib/inflate");v=v("./lib/zlib/constants");var h={};y(h,x,r,v);J.exports=h},{"./lib/deflate":25,"./lib/inflate":26,"./lib/utils/common":27,"./lib/zlib/constants":30}],25:[function(v,J,y){function x(k,l){l=new t(l);l.push(k,!0);if(l.err)throw l.msg;return l.result}var r=v("./zlib/deflate.js"),h=v("./utils/common"),A=v("./utils/strings"),w=v("./zlib/messages"),f=v("./zlib/zstream"),
t=function(k){k=this.options=h.assign({level:-1,method:8,chunkSize:16384,windowBits:15,memLevel:8,strategy:0,to:""},k||{});k.raw&&0<k.windowBits?k.windowBits=-k.windowBits:k.gzip&&0<k.windowBits&&16>k.windowBits&&(k.windowBits+=16);this.err=0;this.msg="";this.ended=!1;this.chunks=[];this.strm=new f;this.strm.avail_out=0;var l=r.deflateInit2(this.strm,k.level,k.method,k.windowBits,k.memLevel,k.strategy);if(0!==l)throw Error(w[l]);k.header&&r.deflateSetHeader(this.strm,k.header)};t.prototype.push=function(k,
l){var p=this.strm,n=this.options.chunkSize;if(this.ended)return!1;l=l===~~l?l:!0===l?4:0;p.input="string"===typeof k?A.string2buf(k):k;p.next_in=0;p.avail_in=p.input.length;do{0===p.avail_out&&(p.output=new h.Buf8(n),p.next_out=0,p.avail_out=n);k=r.deflate(p,l);if(1!==k&&0!==k)return this.onEnd(k),this.ended=!0,!1;if(0===p.avail_out||0===p.avail_in&&4===l)if("string"===this.options.to)this.onData(A.buf2binstring(h.shrinkBuf(p.output,p.next_out)));else this.onData(h.shrinkBuf(p.output,p.next_out))}while((0<
p.avail_in||0===p.avail_out)&&1!==k);return 4===l?(k=r.deflateEnd(this.strm),this.onEnd(k),this.ended=!0,0===k):!0};t.prototype.onData=function(k){this.chunks.push(k)};t.prototype.onEnd=function(k){0===k&&(this.result="string"===this.options.to?this.chunks.join(""):h.flattenChunks(this.chunks));this.chunks=[];this.err=k;this.msg=this.strm.msg};y.Deflate=t;y.deflate=x;y.deflateRaw=function(k,l){l=l||{};l.raw=!0;return x(k,l)};y.gzip=function(k,l){l=l||{};l.gzip=!0;return x(k,l)}},{"./utils/common":27,
"./utils/strings":28,"./zlib/deflate.js":32,"./zlib/messages":37,"./zlib/zstream":39}],26:[function(v,J,y){function x(p,n){n=new l(n);n.push(p,!0);if(n.err)throw n.msg;return n.result}var r=v("./zlib/inflate.js"),h=v("./utils/common"),A=v("./utils/strings"),w=v("./zlib/constants"),f=v("./zlib/messages"),t=v("./zlib/zstream"),k=v("./zlib/gzheader"),l=function(p){var n=this.options=h.assign({chunkSize:16384,windowBits:0,to:""},p||{});n.raw&&0<=n.windowBits&&16>n.windowBits&&(n.windowBits=-n.windowBits,
0===n.windowBits&&(n.windowBits=-15));!(0<=n.windowBits&&16>n.windowBits)||p&&p.windowBits||(n.windowBits+=32);15<n.windowBits&&48>n.windowBits&&0===(n.windowBits&15)&&(n.windowBits|=15);this.err=0;this.msg="";this.ended=!1;this.chunks=[];this.strm=new t;this.strm.avail_out=0;p=r.inflateInit2(this.strm,n.windowBits);if(p!==w.Z_OK)throw Error(f[p]);this.header=new k;r.inflateGetHeader(this.strm,this.header)};l.prototype.push=function(p,n){var G=this.strm,O=this.options.chunkSize;if(this.ended)return!1;
n=n===~~n?n:!0===n?w.Z_FINISH:w.Z_NO_FLUSH;G.input="string"===typeof p?A.binstring2buf(p):p;G.next_in=0;G.avail_in=G.input.length;do{0===G.avail_out&&(G.output=new h.Buf8(O),G.next_out=0,G.avail_out=O);p=r.inflate(G,w.Z_NO_FLUSH);if(p!==w.Z_STREAM_END&&p!==w.Z_OK)return this.onEnd(p),this.ended=!0,!1;if(G.next_out&&(0===G.avail_out||p===w.Z_STREAM_END||0===G.avail_in&&n===w.Z_FINISH))if("string"===this.options.to){var T=A.utf8border(G.output,G.next_out);var u=G.next_out-T;var D=A.buf2string(G.output,
T);G.next_out=u;G.avail_out=O-u;u&&h.arraySet(G.output,G.output,T,u,0);this.onData(D)}else this.onData(h.shrinkBuf(G.output,G.next_out))}while(0<G.avail_in&&p!==w.Z_STREAM_END);p===w.Z_STREAM_END&&(n=w.Z_FINISH);return n===w.Z_FINISH?(p=r.inflateEnd(this.strm),this.onEnd(p),this.ended=!0,p===w.Z_OK):!0};l.prototype.onData=function(p){this.chunks.push(p)};l.prototype.onEnd=function(p){p===w.Z_OK&&(this.result="string"===this.options.to?this.chunks.join(""):h.flattenChunks(this.chunks));this.chunks=
[];this.err=p;this.msg=this.strm.msg};y.Inflate=l;y.inflate=x;y.inflateRaw=function(p,n){n=n||{};n.raw=!0;return x(p,n)};y.ungzip=x},{"./utils/common":27,"./utils/strings":28,"./zlib/constants":30,"./zlib/gzheader":33,"./zlib/inflate.js":35,"./zlib/messages":37,"./zlib/zstream":39}],27:[function(v,J,y){v="undefined"!==typeof Uint8Array&&"undefined"!==typeof Uint16Array&&"undefined"!==typeof Int32Array;y.assign=function(h){for(var A=Array.prototype.slice.call(arguments,1);A.length;){var w=A.shift();
if(w){if("object"!==typeof w)throw new TypeError(w+"must be non-object");for(var f in w)w.hasOwnProperty(f)&&(h[f]=w[f])}}return h};y.shrinkBuf=function(h,A){if(h.length===A)return h;if(h.subarray)return h.subarray(0,A);h.length=A;return h};var x={arraySet:function(h,A,w,f,t){if(A.subarray&&h.subarray)h.set(A.subarray(w,w+f),t);else for(var k=0;k<f;k++)h[t+k]=A[w+k]},flattenChunks:function(h){var A,w;var f=w=0;for(A=h.length;f<A;f++)w+=h[f].length;var t=new Uint8Array(w);f=w=0;for(A=h.length;f<A;f++){var k=
h[f];t.set(k,w);w+=k.length}return t}},r={arraySet:function(h,A,w,f,t){for(var k=0;k<f;k++)h[t+k]=A[w+k]},flattenChunks:function(h){return[].concat.apply([],h)}};y.setTyped=function(h){h?(y.Buf8=Uint8Array,y.Buf16=Uint16Array,y.Buf32=Int32Array,y.assign(y,x)):(y.Buf8=Array,y.Buf16=Array,y.Buf32=Array,y.assign(y,r))};y.setTyped(v)},{}],28:[function(v,J,y){function x(f,t){if(65537>t&&(f.subarray&&A||!f.subarray&&h))return String.fromCharCode.apply(null,r.shrinkBuf(f,t));for(var k="",l=0;l<t;l++)k+=
String.fromCharCode(f[l]);return k}var r=v("./common"),h=!0,A=!0;try{String.fromCharCode.apply(null,[0])}catch(f){h=!1}try{String.fromCharCode.apply(null,new Uint8Array(1))}catch(f){A=!1}var w=new r.Buf8(256);for(v=0;256>v;v++)w[v]=252<=v?6:248<=v?5:240<=v?4:224<=v?3:192<=v?2:1;w[254]=w[254]=1;y.string2buf=function(f){var t,k,l=f.length,p=0;for(t=0;t<l;t++){var n=f.charCodeAt(t);if(55296===(n&64512)&&t+1<l){var G=f.charCodeAt(t+1);56320===(G&64512)&&(n=65536+(n-55296<<10)+(G-56320),t++)}p+=128>n?
1:2048>n?2:65536>n?3:4}var O=new r.Buf8(p);for(t=k=0;k<p;t++)n=f.charCodeAt(t),55296===(n&64512)&&t+1<l&&(G=f.charCodeAt(t+1),56320===(G&64512)&&(n=65536+(n-55296<<10)+(G-56320),t++)),128>n?O[k++]=n:(2048>n?O[k++]=192|n>>>6:(65536>n?O[k++]=224|n>>>12:(O[k++]=240|n>>>18,O[k++]=128|n>>>12&63),O[k++]=128|n>>>6&63),O[k++]=128|n&63);return O};y.buf2binstring=function(f){return x(f,f.length)};y.binstring2buf=function(f){for(var t=new r.Buf8(f.length),k=0,l=t.length;k<l;k++)t[k]=f.charCodeAt(k);return t};
y.buf2string=function(f,t){var k,l=t||f.length,p=Array(2*l);for(t=k=0;t<l;){var n=f[t++];if(128>n)p[k++]=n;else{var G=w[n];if(4<G)p[k++]=65533,t+=G-1;else{for(n&=2===G?31:3===G?15:7;1<G&&t<l;)n=n<<6|f[t++]&63,G--;1<G?p[k++]=65533:65536>n?p[k++]=n:(n-=65536,p[k++]=55296|n>>10&1023,p[k++]=56320|n&1023)}}}return x(p,k)};y.utf8border=function(f,t){var k;t=t||f.length;t>f.length&&(t=f.length);for(k=t-1;0<=k&&128===(f[k]&192);)k--;return 0>k||0===k?t:k+w[f[k]]>t?k:t}},{"./common":27}],29:[function(v,J,
y){J.exports=function(x,r,h,A){var w=x&65535|0;x=x>>>16&65535|0;for(var f;0!==h;){f=2E3<h?2E3:h;h-=f;do w=w+r[A++]|0,x=x+w|0;while(--f);w%=65521;x%=65521}return w|x<<16|0}},{}],30:[function(v,J,y){J.exports={Z_NO_FLUSH:0,Z_PARTIAL_FLUSH:1,Z_SYNC_FLUSH:2,Z_FULL_FLUSH:3,Z_FINISH:4,Z_BLOCK:5,Z_TREES:6,Z_OK:0,Z_STREAM_END:1,Z_NEED_DICT:2,Z_ERRNO:-1,Z_STREAM_ERROR:-2,Z_DATA_ERROR:-3,Z_BUF_ERROR:-5,Z_NO_COMPRESSION:0,Z_BEST_SPEED:1,Z_BEST_COMPRESSION:9,Z_DEFAULT_COMPRESSION:-1,Z_FILTERED:1,Z_HUFFMAN_ONLY:2,
Z_RLE:3,Z_FIXED:4,Z_DEFAULT_STRATEGY:0,Z_BINARY:0,Z_TEXT:1,Z_UNKNOWN:2,Z_DEFLATED:8}},{}],31:[function(v,J,y){var x=function(){for(var r,h=[],A=0;256>A;A++){r=A;for(var w=0;8>w;w++)r=r&1?3988292384^r>>>1:r>>>1;h[A]=r}return h}();J.exports=function(r,h,A,w){A=w+A;for(r^=-1;w<A;w++)r=r>>>8^x[(r^h[w])&255];return r^-1}},{}],32:[function(v,J,y){function x(a,e){a.msg=P[e];return e}function r(a){for(var e=a.length;0<=--e;)a[e]=0}function h(a){var e=a.state,b=e.pending;b>a.avail_out&&(b=a.avail_out);0!==
b&&(L.arraySet(a.output,e.pending_buf,e.pending_out,b,a.next_out),a.next_out+=b,e.pending_out+=b,a.total_out+=b,a.avail_out-=b,e.pending-=b,0===e.pending&&(e.pending_out=0))}function A(a,e){N._tr_flush_block(a,0<=a.block_start?a.block_start:-1,a.strstart-a.block_start,e);a.block_start=a.strstart;h(a.strm)}function w(a,e){a.pending_buf[a.pending++]=e}function f(a,e){a.pending_buf[a.pending++]=e>>>8&255;a.pending_buf[a.pending++]=e&255}function t(a,e){var b=a.max_chain_length,m=a.strstart,g=a.prev_length,
q=a.nice_match,S=a.strstart>a.w_size-262?a.strstart-(a.w_size-262):0,E=a.window,R=a.w_mask,H=a.prev,B=a.strstart+258,d=E[m+g-1],z=E[m+g];a.prev_length>=a.good_match&&(b>>=2);q>a.lookahead&&(q=a.lookahead);do{var C=e;if(E[C+g]===z&&E[C+g-1]===d&&E[C]===E[m]&&E[++C]===E[m+1]){m+=2;for(C++;E[++m]===E[++C]&&E[++m]===E[++C]&&E[++m]===E[++C]&&E[++m]===E[++C]&&E[++m]===E[++C]&&E[++m]===E[++C]&&E[++m]===E[++C]&&E[++m]===E[++C]&&m<B;);C=258-(B-m);m=B-258;if(C>g){a.match_start=e;g=C;if(C>=q)break;d=E[m+g-1];
z=E[m+g]}}}while((e=H[e&R])>S&&0!==--b);return g<=a.lookahead?g:a.lookahead}function k(a){var e=a.w_size,b;do{var m=a.window_size-a.lookahead-a.strstart;if(a.strstart>=e+(e-262)){L.arraySet(a.window,a.window,e,e,0);a.match_start-=e;a.strstart-=e;a.block_start-=e;var g=b=a.hash_size;do{var q=a.head[--g];a.head[g]=q>=e?q-e:0}while(--b);g=b=e;do q=a.prev[--g],a.prev[g]=q>=e?q-e:0;while(--b);m+=e}if(0===a.strm.avail_in)break;g=a.strm;b=a.window;q=a.strstart+a.lookahead;var S=g.avail_in;S>m&&(S=m);0===
S?b=0:(g.avail_in-=S,L.arraySet(b,g.input,g.next_in,S,q),1===g.state.wrap?g.adler=W(g.adler,b,S,q):2===g.state.wrap&&(g.adler=c(g.adler,b,S,q)),g.next_in+=S,g.total_in+=S,b=S);a.lookahead+=b;if(3<=a.lookahead+a.insert)for(m=a.strstart-a.insert,a.ins_h=a.window[m],a.ins_h=(a.ins_h<<a.hash_shift^a.window[m+1])&a.hash_mask;a.insert&&!(a.ins_h=(a.ins_h<<a.hash_shift^a.window[m+3-1])&a.hash_mask,a.prev[m&a.w_mask]=a.head[a.ins_h],a.head[a.ins_h]=m,m++,a.insert--,3>a.lookahead+a.insert););}while(262>a.lookahead&&
0!==a.strm.avail_in)}function l(a,e){for(var b;;){if(262>a.lookahead){k(a);if(262>a.lookahead&&0===e)return 1;if(0===a.lookahead)break}b=0;3<=a.lookahead&&(a.ins_h=(a.ins_h<<a.hash_shift^a.window[a.strstart+3-1])&a.hash_mask,b=a.prev[a.strstart&a.w_mask]=a.head[a.ins_h],a.head[a.ins_h]=a.strstart);0!==b&&a.strstart-b<=a.w_size-262&&(a.match_length=t(a,b));if(3<=a.match_length)if(b=N._tr_tally(a,a.strstart-a.match_start,a.match_length-3),a.lookahead-=a.match_length,a.match_length<=a.max_lazy_match&&
3<=a.lookahead){a.match_length--;do a.strstart++,a.ins_h=(a.ins_h<<a.hash_shift^a.window[a.strstart+3-1])&a.hash_mask,a.prev[a.strstart&a.w_mask]=a.head[a.ins_h],a.head[a.ins_h]=a.strstart;while(0!==--a.match_length);a.strstart++}else a.strstart+=a.match_length,a.match_length=0,a.ins_h=a.window[a.strstart],a.ins_h=(a.ins_h<<a.hash_shift^a.window[a.strstart+1])&a.hash_mask;else b=N._tr_tally(a,0,a.window[a.strstart]),a.lookahead--,a.strstart++;if(b&&(A(a,!1),0===a.strm.avail_out))return 1}a.insert=
2>a.strstart?a.strstart:2;return 4===e?(A(a,!0),0===a.strm.avail_out?3:4):a.last_lit&&(A(a,!1),0===a.strm.avail_out)?1:2}function p(a,e){for(var b,m;;){if(262>a.lookahead){k(a);if(262>a.lookahead&&0===e)return 1;if(0===a.lookahead)break}b=0;3<=a.lookahead&&(a.ins_h=(a.ins_h<<a.hash_shift^a.window[a.strstart+3-1])&a.hash_mask,b=a.prev[a.strstart&a.w_mask]=a.head[a.ins_h],a.head[a.ins_h]=a.strstart);a.prev_length=a.match_length;a.prev_match=a.match_start;a.match_length=2;0!==b&&a.prev_length<a.max_lazy_match&&
a.strstart-b<=a.w_size-262&&(a.match_length=t(a,b),5>=a.match_length&&(1===a.strategy||3===a.match_length&&4096<a.strstart-a.match_start)&&(a.match_length=2));if(3<=a.prev_length&&a.match_length<=a.prev_length){m=a.strstart+a.lookahead-3;b=N._tr_tally(a,a.strstart-1-a.prev_match,a.prev_length-3);a.lookahead-=a.prev_length-1;a.prev_length-=2;do++a.strstart<=m&&(a.ins_h=(a.ins_h<<a.hash_shift^a.window[a.strstart+3-1])&a.hash_mask,a.prev[a.strstart&a.w_mask]=a.head[a.ins_h],a.head[a.ins_h]=a.strstart);
while(0!==--a.prev_length);a.match_available=0;a.match_length=2;a.strstart++;if(b&&(A(a,!1),0===a.strm.avail_out))return 1}else if(a.match_available){if((b=N._tr_tally(a,0,a.window[a.strstart-1]))&&A(a,!1),a.strstart++,a.lookahead--,0===a.strm.avail_out)return 1}else a.match_available=1,a.strstart++,a.lookahead--}a.match_available&&(N._tr_tally(a,0,a.window[a.strstart-1]),a.match_available=0);a.insert=2>a.strstart?a.strstart:2;return 4===e?(A(a,!0),0===a.strm.avail_out?3:4):a.last_lit&&(A(a,!1),0===
a.strm.avail_out)?1:2}function n(a,e){for(var b,m,g,q=a.window;;){if(258>=a.lookahead){k(a);if(258>=a.lookahead&&0===e)return 1;if(0===a.lookahead)break}a.match_length=0;if(3<=a.lookahead&&0<a.strstart&&(m=a.strstart-1,b=q[m],b===q[++m]&&b===q[++m]&&b===q[++m])){for(g=a.strstart+258;b===q[++m]&&b===q[++m]&&b===q[++m]&&b===q[++m]&&b===q[++m]&&b===q[++m]&&b===q[++m]&&b===q[++m]&&m<g;);a.match_length=258-(g-m);a.match_length>a.lookahead&&(a.match_length=a.lookahead)}3<=a.match_length?(b=N._tr_tally(a,
1,a.match_length-3),a.lookahead-=a.match_length,a.strstart+=a.match_length,a.match_length=0):(b=N._tr_tally(a,0,a.window[a.strstart]),a.lookahead--,a.strstart++);if(b&&(A(a,!1),0===a.strm.avail_out))return 1}a.insert=0;return 4===e?(A(a,!0),0===a.strm.avail_out?3:4):a.last_lit&&(A(a,!1),0===a.strm.avail_out)?1:2}function G(a,e){for(var b;;){if(0===a.lookahead&&(k(a),0===a.lookahead)){if(0===e)return 1;break}a.match_length=0;b=N._tr_tally(a,0,a.window[a.strstart]);a.lookahead--;a.strstart++;if(b&&
(A(a,!1),0===a.strm.avail_out))return 1}a.insert=0;return 4===e?(A(a,!0),0===a.strm.avail_out?3:4):a.last_lit&&(A(a,!1),0===a.strm.avail_out)?1:2}function O(){this.strm=null;this.status=0;this.pending_buf=null;this.wrap=this.pending=this.pending_out=this.pending_buf_size=0;this.gzhead=null;this.gzindex=0;this.method=8;this.last_flush=-1;this.w_mask=this.w_bits=this.w_size=0;this.window=null;this.window_size=0;this.head=this.prev=null;this.nice_match=this.good_match=this.strategy=this.level=this.max_lazy_match=
this.max_chain_length=this.prev_length=this.lookahead=this.match_start=this.strstart=this.match_available=this.prev_match=this.match_length=this.block_start=this.hash_shift=this.hash_mask=this.hash_bits=this.hash_size=this.ins_h=0;this.dyn_ltree=new L.Buf16(1146);this.dyn_dtree=new L.Buf16(122);this.bl_tree=new L.Buf16(78);r(this.dyn_ltree);r(this.dyn_dtree);r(this.bl_tree);this.bl_desc=this.d_desc=this.l_desc=null;this.bl_count=new L.Buf16(16);this.heap=new L.Buf16(573);r(this.heap);this.heap_max=
this.heap_len=0;this.depth=new L.Buf16(573);r(this.depth);this.bi_valid=this.bi_buf=this.insert=this.matches=this.static_len=this.opt_len=this.d_buf=this.last_lit=this.lit_bufsize=this.l_buf=0}function T(a){if(!a||!a.state)return x(a,-2);a.total_in=a.total_out=0;a.data_type=2;var e=a.state;e.pending=0;e.pending_out=0;0>e.wrap&&(e.wrap=-e.wrap);e.status=e.wrap?42:113;a.adler=2===e.wrap?0:1;e.last_flush=0;N._tr_init(e);return 0}function u(a){var e=T(a);0===e&&(a=a.state,a.window_size=2*a.w_size,r(a.head),
a.max_lazy_match=F[a.level].max_lazy,a.good_match=F[a.level].good_length,a.nice_match=F[a.level].nice_length,a.max_chain_length=F[a.level].max_chain,a.strstart=0,a.block_start=0,a.lookahead=0,a.insert=0,a.match_length=a.prev_length=2,a.match_available=0,a.ins_h=0);return e}function D(a,e,b,m,g,q){if(!a)return-2;var S=1;-1===e&&(e=6);0>m?(S=0,m=-m):15<m&&(S=2,m-=16);if(1>g||9<g||8!==b||8>m||15<m||0>e||9<e||0>q||4<q)return x(a,-2);8===m&&(m=9);var E=new O;a.state=E;E.strm=a;E.wrap=S;E.gzhead=null;E.w_bits=
m;E.w_size=1<<E.w_bits;E.w_mask=E.w_size-1;E.hash_bits=g+7;E.hash_size=1<<E.hash_bits;E.hash_mask=E.hash_size-1;E.hash_shift=~~((E.hash_bits+3-1)/3);E.window=new L.Buf8(2*E.w_size);E.head=new L.Buf16(E.hash_size);E.prev=new L.Buf16(E.w_size);E.lit_bufsize=1<<g+6;E.pending_buf_size=4*E.lit_bufsize;E.pending_buf=new L.Buf8(E.pending_buf_size);E.d_buf=E.lit_bufsize>>1;E.l_buf=3*E.lit_bufsize;E.level=e;E.strategy=q;E.method=b;return u(a)}var L=v("../utils/common"),N=v("./trees"),W=v("./adler32"),c=v("./crc32"),
P=v("./messages");v=function(a,e,b,m,g){this.good_length=a;this.max_lazy=e;this.nice_length=b;this.max_chain=m;this.func=g};var F=[new v(0,0,0,0,function(a,e){var b=65535;for(b>a.pending_buf_size-5&&(b=a.pending_buf_size-5);;){if(1>=a.lookahead){k(a);if(0===a.lookahead&&0===e)return 1;if(0===a.lookahead)break}a.strstart+=a.lookahead;a.lookahead=0;var m=a.block_start+b;if(0===a.strstart||a.strstart>=m)if(a.lookahead=a.strstart-m,a.strstart=m,A(a,!1),0===a.strm.avail_out)return 1;if(a.strstart-a.block_start>=
a.w_size-262&&(A(a,!1),0===a.strm.avail_out))return 1}a.insert=0;if(4===e)return A(a,!0),0===a.strm.avail_out?3:4;a.strstart>a.block_start&&A(a,!1);return 1}),new v(4,4,8,4,l),new v(4,5,16,8,l),new v(4,6,32,32,l),new v(4,4,16,16,p),new v(8,16,32,32,p),new v(8,16,128,128,p),new v(8,32,128,256,p),new v(32,128,258,1024,p),new v(32,258,258,4096,p)];y.deflateInit=function(a,e){return D(a,e,8,15,8,0)};y.deflateInit2=D;y.deflateReset=u;y.deflateResetKeep=T;y.deflateSetHeader=function(a,e){if(!a||!a.state||
2!==a.state.wrap)return-2;a.state.gzhead=e;return 0};y.deflate=function(a,e){if(!a||!a.state||5<e||0>e)return a?x(a,-2):-2;var b=a.state;if(!a.output||!a.input&&0!==a.avail_in||666===b.status&&4!==e)return x(a,0===a.avail_out?-5:-2);b.strm=a;var m=b.last_flush;b.last_flush=e;if(42===b.status)if(2===b.wrap)a.adler=0,w(b,31),w(b,139),w(b,8),b.gzhead?(w(b,(b.gzhead.text?1:0)+(b.gzhead.hcrc?2:0)+(b.gzhead.extra?4:0)+(b.gzhead.name?8:0)+(b.gzhead.comment?16:0)),w(b,b.gzhead.time&255),w(b,b.gzhead.time>>
8&255),w(b,b.gzhead.time>>16&255),w(b,b.gzhead.time>>24&255),w(b,9===b.level?2:2<=b.strategy||2>b.level?4:0),w(b,b.gzhead.os&255),b.gzhead.extra&&b.gzhead.extra.length&&(w(b,b.gzhead.extra.length&255),w(b,b.gzhead.extra.length>>8&255)),b.gzhead.hcrc&&(a.adler=c(a.adler,b.pending_buf,b.pending,0)),b.gzindex=0,b.status=69):(w(b,0),w(b,0),w(b,0),w(b,0),w(b,0),w(b,9===b.level?2:2<=b.strategy||2>b.level?4:0),w(b,3),b.status=113);else{var g=8+(b.w_bits-8<<4)<<8;g|=(2<=b.strategy||2>b.level?0:6>b.level?
1:6===b.level?2:3)<<6;0!==b.strstart&&(g|=32);b.status=113;f(b,g+(31-g%31));0!==b.strstart&&(f(b,a.adler>>>16),f(b,a.adler&65535));a.adler=1}if(69===b.status)if(b.gzhead.extra){for(g=b.pending;b.gzindex<(b.gzhead.extra.length&65535)&&(b.pending!==b.pending_buf_size||(b.gzhead.hcrc&&b.pending>g&&(a.adler=c(a.adler,b.pending_buf,b.pending-g,g)),h(a),g=b.pending,b.pending!==b.pending_buf_size));)w(b,b.gzhead.extra[b.gzindex]&255),b.gzindex++;b.gzhead.hcrc&&b.pending>g&&(a.adler=c(a.adler,b.pending_buf,
b.pending-g,g));b.gzindex===b.gzhead.extra.length&&(b.gzindex=0,b.status=73)}else b.status=73;if(73===b.status)if(b.gzhead.name){g=b.pending;do{if(b.pending===b.pending_buf_size&&(b.gzhead.hcrc&&b.pending>g&&(a.adler=c(a.adler,b.pending_buf,b.pending-g,g)),h(a),g=b.pending,b.pending===b.pending_buf_size)){var q=1;break}q=b.gzindex<b.gzhead.name.length?b.gzhead.name.charCodeAt(b.gzindex++)&255:0;w(b,q)}while(0!==q);b.gzhead.hcrc&&b.pending>g&&(a.adler=c(a.adler,b.pending_buf,b.pending-g,g));0===q&&
(b.gzindex=0,b.status=91)}else b.status=91;if(91===b.status)if(b.gzhead.comment){g=b.pending;do{if(b.pending===b.pending_buf_size&&(b.gzhead.hcrc&&b.pending>g&&(a.adler=c(a.adler,b.pending_buf,b.pending-g,g)),h(a),g=b.pending,b.pending===b.pending_buf_size)){q=1;break}q=b.gzindex<b.gzhead.comment.length?b.gzhead.comment.charCodeAt(b.gzindex++)&255:0;w(b,q)}while(0!==q);b.gzhead.hcrc&&b.pending>g&&(a.adler=c(a.adler,b.pending_buf,b.pending-g,g));0===q&&(b.status=103)}else b.status=103;103===b.status&&
(b.gzhead.hcrc?(b.pending+2>b.pending_buf_size&&h(a),b.pending+2<=b.pending_buf_size&&(w(b,a.adler&255),w(b,a.adler>>8&255),a.adler=0,b.status=113)):b.status=113);if(0!==b.pending){if(h(a),0===a.avail_out)return b.last_flush=-1,0}else if(0===a.avail_in&&(e<<1)-(4<e?9:0)<=(m<<1)-(4<m?9:0)&&4!==e)return x(a,-5);if(666===b.status&&0!==a.avail_in)return x(a,-5);if(0!==a.avail_in||0!==b.lookahead||0!==e&&666!==b.status){m=2===b.strategy?G(b,e):3===b.strategy?n(b,e):F[b.level].func(b,e);if(3===m||4===m)b.status=
666;if(1===m||3===m)return 0===a.avail_out&&(b.last_flush=-1),0;if(2===m&&(1===e?N._tr_align(b):5!==e&&(N._tr_stored_block(b,0,0,!1),3===e&&(r(b.head),0===b.lookahead&&(b.strstart=0,b.block_start=0,b.insert=0))),h(a),0===a.avail_out))return b.last_flush=-1,0}if(4!==e)return 0;if(0>=b.wrap)return 1;2===b.wrap?(w(b,a.adler&255),w(b,a.adler>>8&255),w(b,a.adler>>16&255),w(b,a.adler>>24&255),w(b,a.total_in&255),w(b,a.total_in>>8&255),w(b,a.total_in>>16&255),w(b,a.total_in>>24&255)):(f(b,a.adler>>>16),
f(b,a.adler&65535));h(a);0<b.wrap&&(b.wrap=-b.wrap);return 0!==b.pending?0:1};y.deflateEnd=function(a){if(!a||!a.state)return-2;var e=a.state.status;if(42!==e&&69!==e&&73!==e&&91!==e&&103!==e&&113!==e&&666!==e)return x(a,-2);a.state=null;return 113===e?x(a,-3):0};y.deflateInfo="pako deflate (from Nodeca project)"},{"../utils/common":27,"./adler32":29,"./crc32":31,"./messages":37,"./trees":38}],33:[function(v,J,y){J.exports=function(){this.os=this.xflags=this.time=this.text=0;this.extra=null;this.extra_len=
0;this.comment=this.name="";this.hcrc=0;this.done=!1}},{}],34:[function(v,J,y){J.exports=function(x,r){var h=x.state;var A=x.next_in;var w=x.input;var f=A+(x.avail_in-5);var t=x.next_out;var k=x.output;r=t-(r-x.avail_out);var l=t+(x.avail_out-257);var p=h.dmax;var n=h.wsize;var G=h.whave;var O=h.wnext;var T=h.window;var u=h.hold;var D=h.bits;var L=h.lencode;var N=h.distcode;var W=(1<<h.lenbits)-1;var c=(1<<h.distbits)-1;a:do{15>D&&(u+=w[A++]<<D,D+=8,u+=w[A++]<<D,D+=8);var P=L[u&W];b:for(;;){var F=
P>>>24;u>>>=F;D-=F;F=P>>>16&255;if(0===F)k[t++]=P&65535;else if(F&16){var a=P&65535;if(F&=15)D<F&&(u+=w[A++]<<D,D+=8),a+=u&(1<<F)-1,u>>>=F,D-=F;15>D&&(u+=w[A++]<<D,D+=8,u+=w[A++]<<D,D+=8);P=N[u&c];c:for(;;){F=P>>>24;u>>>=F;D-=F;F=P>>>16&255;if(F&16){P&=65535;F&=15;D<F&&(u+=w[A++]<<D,D+=8,D<F&&(u+=w[A++]<<D,D+=8));P+=u&(1<<F)-1;if(P>p){x.msg="invalid distance too far back";h.mode=30;break a}u>>>=F;D-=F;F=t-r;if(P>F){F=P-F;if(F>G&&h.sane){x.msg="invalid distance too far back";h.mode=30;break a}var e=
0;var b=T;if(0===O){if(e+=n-F,F<a){a-=F;do k[t++]=T[e++];while(--F);e=t-P;b=k}}else if(O<F){if(e+=n+O-F,F-=O,F<a){a-=F;do k[t++]=T[e++];while(--F);e=0;if(O<a){F=O;a-=F;do k[t++]=T[e++];while(--F);e=t-P;b=k}}}else if(e+=O-F,F<a){a-=F;do k[t++]=T[e++];while(--F);e=t-P;b=k}for(;2<a;)k[t++]=b[e++],k[t++]=b[e++],k[t++]=b[e++],a-=3;a&&(k[t++]=b[e++],1<a&&(k[t++]=b[e++]))}else{e=t-P;do k[t++]=k[e++],k[t++]=k[e++],k[t++]=k[e++],a-=3;while(2<a);a&&(k[t++]=k[e++],1<a&&(k[t++]=k[e++]))}}else if(0===(F&64)){P=
N[(P&65535)+(u&(1<<F)-1)];continue c}else{x.msg="invalid distance code";h.mode=30;break a}break}}else if(0===(F&64)){P=L[(P&65535)+(u&(1<<F)-1)];continue b}else{F&32?h.mode=12:(x.msg="invalid literal/length code",h.mode=30);break a}break}}while(A<f&&t<l);a=D>>3;A-=a;D-=a<<3;x.next_in=A;x.next_out=t;x.avail_in=A<f?5+(f-A):5-(A-f);x.avail_out=t<l?257+(l-t):257-(t-l);h.hold=u&(1<<D)-1;h.bits=D}},{}],35:[function(v,J,y){function x(u){return(u>>>24&255)+(u>>>8&65280)+((u&65280)<<8)+((u&255)<<24)}function r(){this.mode=
0;this.last=!1;this.wrap=0;this.havedict=!1;this.total=this.check=this.dmax=this.flags=0;this.head=null;this.wnext=this.whave=this.wsize=this.wbits=0;this.window=null;this.extra=this.offset=this.length=this.bits=this.hold=0;this.distcode=this.lencode=null;this.have=this.ndist=this.nlen=this.ncode=this.distbits=this.lenbits=0;this.next=null;this.lens=new t.Buf16(320);this.work=new t.Buf16(288);this.distdyn=this.lendyn=null;this.was=this.back=this.sane=0}function h(u){if(!u||!u.state)return-2;var D=
u.state;u.total_in=u.total_out=D.total=0;u.msg="";D.wrap&&(u.adler=D.wrap&1);D.mode=1;D.last=0;D.havedict=0;D.dmax=32768;D.head=null;D.hold=0;D.bits=0;D.lencode=D.lendyn=new t.Buf32(852);D.distcode=D.distdyn=new t.Buf32(592);D.sane=1;D.back=-1;return 0}function A(u){if(!u||!u.state)return-2;var D=u.state;D.wsize=0;D.whave=0;D.wnext=0;return h(u)}function w(u,D){if(!u||!u.state)return-2;var L=u.state;if(0>D){var N=0;D=-D}else N=(D>>4)+1,48>D&&(D&=15);if(D&&(8>D||15<D))return-2;null!==L.window&&L.wbits!==
D&&(L.window=null);L.wrap=N;L.wbits=D;return A(u)}function f(u,D){if(!u)return-2;var L=new r;u.state=L;L.window=null;D=w(u,D);0!==D&&(u.state=null);return D}var t=v("../utils/common"),k=v("./adler32"),l=v("./crc32"),p=v("./inffast"),n=v("./inftrees"),G=!0,O,T;y.inflateReset=A;y.inflateReset2=w;y.inflateResetKeep=h;y.inflateInit=function(u){return f(u,15)};y.inflateInit2=f;y.inflate=function(u,D){var L,N=new t.Buf8(4),W=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15];if(!u||!u.state||!u.output||!u.input&&
0!==u.avail_in)return-2;var c=u.state;12===c.mode&&(c.mode=13);var P=u.next_out;var F=u.output;var a=u.avail_out;var e=u.next_in;var b=u.input;var m=u.avail_in;var g=c.hold;var q=c.bits;var S=m;var E=a;var R=0;a:for(;;)switch(c.mode){case 1:if(0===c.wrap){c.mode=13;break}for(;16>q;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}if(c.wrap&2&&35615===g){c.check=0;N[0]=g&255;N[1]=g>>>8&255;c.check=l(c.check,N,2,0);q=g=0;c.mode=2;break}c.flags=0;c.head&&(c.head.done=!1);if(!(c.wrap&1)||(((g&255)<<8)+(g>>8))%
31){u.msg="incorrect header check";c.mode=30;break}if(8!==(g&15)){u.msg="unknown compression method";c.mode=30;break}g>>>=4;q-=4;var H=(g&15)+8;if(0===c.wbits)c.wbits=H;else if(H>c.wbits){u.msg="invalid window size";c.mode=30;break}c.dmax=1<<H;u.adler=c.check=1;c.mode=g&512?10:12;q=g=0;break;case 2:for(;16>q;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}c.flags=g;if(8!==(c.flags&255)){u.msg="unknown compression method";c.mode=30;break}if(c.flags&57344){u.msg="unknown header flags set";c.mode=30;break}c.head&&
(c.head.text=g>>8&1);c.flags&512&&(N[0]=g&255,N[1]=g>>>8&255,c.check=l(c.check,N,2,0));q=g=0;c.mode=3;case 3:for(;32>q;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}c.head&&(c.head.time=g);c.flags&512&&(N[0]=g&255,N[1]=g>>>8&255,N[2]=g>>>16&255,N[3]=g>>>24&255,c.check=l(c.check,N,4,0));q=g=0;c.mode=4;case 4:for(;16>q;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}c.head&&(c.head.xflags=g&255,c.head.os=g>>8);c.flags&512&&(N[0]=g&255,N[1]=g>>>8&255,c.check=l(c.check,N,2,0));q=g=0;c.mode=5;case 5:if(c.flags&1024){for(;16>
q;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}c.length=g;c.head&&(c.head.extra_len=g);c.flags&512&&(N[0]=g&255,N[1]=g>>>8&255,c.check=l(c.check,N,2,0));q=g=0}else c.head&&(c.head.extra=null);c.mode=6;case 6:if(c.flags&1024){var B=c.length;B>m&&(B=m);B&&(c.head&&(H=c.head.extra_len-c.length,c.head.extra||(c.head.extra=Array(c.head.extra_len)),t.arraySet(c.head.extra,b,e,B,H)),c.flags&512&&(c.check=l(c.check,b,B,e)),m-=B,e+=B,c.length-=B);if(c.length)break a}c.length=0;c.mode=7;case 7:if(c.flags&2048){if(0===
m)break a;B=0;do H=b[e+B++],c.head&&H&&65536>c.length&&(c.head.name+=String.fromCharCode(H));while(H&&B<m);c.flags&512&&(c.check=l(c.check,b,B,e));m-=B;e+=B;if(H)break a}else c.head&&(c.head.name=null);c.length=0;c.mode=8;case 8:if(c.flags&4096){if(0===m)break a;B=0;do H=b[e+B++],c.head&&H&&65536>c.length&&(c.head.comment+=String.fromCharCode(H));while(H&&B<m);c.flags&512&&(c.check=l(c.check,b,B,e));m-=B;e+=B;if(H)break a}else c.head&&(c.head.comment=null);c.mode=9;case 9:if(c.flags&512){for(;16>
q;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}if(g!==(c.check&65535)){u.msg="header crc mismatch";c.mode=30;break}q=g=0}c.head&&(c.head.hcrc=c.flags>>9&1,c.head.done=!0);u.adler=c.check=0;c.mode=12;break;case 10:for(;32>q;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}u.adler=c.check=x(g);q=g=0;c.mode=11;case 11:if(0===c.havedict)return u.next_out=P,u.avail_out=a,u.next_in=e,u.avail_in=m,c.hold=g,c.bits=q,2;u.adler=c.check=1;c.mode=12;case 12:if(5===D||6===D)break a;case 13:if(c.last){g>>>=q&7;q-=q&7;c.mode=
27;break}for(;3>q;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}c.last=g&1;g>>>=1;--q;switch(g&3){case 0:c.mode=14;break;case 1:H=c;if(G){O=new t.Buf32(512);T=new t.Buf32(32);for(B=0;144>B;)H.lens[B++]=8;for(;256>B;)H.lens[B++]=9;for(;280>B;)H.lens[B++]=7;for(;288>B;)H.lens[B++]=8;n(1,H.lens,0,288,O,0,H.work,{bits:9});for(B=0;32>B;)H.lens[B++]=5;n(2,H.lens,0,32,T,0,H.work,{bits:5});G=!1}H.lencode=O;H.lenbits=9;H.distcode=T;H.distbits=5;c.mode=20;if(6===D){g>>>=2;q-=2;break a}break;case 2:c.mode=17;break;
case 3:u.msg="invalid block type",c.mode=30}g>>>=2;q-=2;break;case 14:g>>>=q&7;for(q-=q&7;32>q;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}if((g&65535)!==(g>>>16^65535)){u.msg="invalid stored block lengths";c.mode=30;break}c.length=g&65535;q=g=0;c.mode=15;if(6===D)break a;case 15:c.mode=16;case 16:if(B=c.length){B>m&&(B=m);B>a&&(B=a);if(0===B)break a;t.arraySet(F,b,e,B,P);m-=B;e+=B;a-=B;P+=B;c.length-=B;break}c.mode=12;break;case 17:for(;14>q;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}c.nlen=(g&31)+257;
g>>>=5;q-=5;c.ndist=(g&31)+1;g>>>=5;q-=5;c.ncode=(g&15)+4;g>>>=4;q-=4;if(286<c.nlen||30<c.ndist){u.msg="too many length or distance symbols";c.mode=30;break}c.have=0;c.mode=18;case 18:for(;c.have<c.ncode;){for(;3>q;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}c.lens[W[c.have++]]=g&7;g>>>=3;q-=3}for(;19>c.have;)c.lens[W[c.have++]]=0;c.lencode=c.lendyn;c.lenbits=7;B={bits:c.lenbits};R=n(0,c.lens,0,19,c.lencode,0,c.work,B);c.lenbits=B.bits;if(R){u.msg="invalid code lengths set";c.mode=30;break}c.have=0;
c.mode=19;case 19:for(;c.have<c.nlen+c.ndist;){for(;;){var d=c.lencode[g&(1<<c.lenbits)-1];B=d>>>24;d&=65535;if(B<=q)break;if(0===m)break a;m--;g+=b[e++]<<q;q+=8}if(16>d)g>>>=B,q-=B,c.lens[c.have++]=d;else{if(16===d){for(H=B+2;q<H;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}g>>>=B;q-=B;if(0===c.have){u.msg="invalid bit length repeat";c.mode=30;break}H=c.lens[c.have-1];B=3+(g&3);g>>>=2;q-=2}else if(17===d){for(H=B+3;q<H;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}g>>>=B;q-=B;H=0;B=3+(g&7);g>>>=3;q-=3}else{for(H=
B+7;q<H;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}g>>>=B;q-=B;H=0;B=11+(g&127);g>>>=7;q-=7}if(c.have+B>c.nlen+c.ndist){u.msg="invalid bit length repeat";c.mode=30;break}for(;B--;)c.lens[c.have++]=H}}if(30===c.mode)break;if(0===c.lens[256]){u.msg="invalid code -- missing end-of-block";c.mode=30;break}c.lenbits=9;B={bits:c.lenbits};R=n(1,c.lens,0,c.nlen,c.lencode,0,c.work,B);c.lenbits=B.bits;if(R){u.msg="invalid literal/lengths set";c.mode=30;break}c.distbits=6;c.distcode=c.distdyn;B={bits:c.distbits};
R=n(2,c.lens,c.nlen,c.ndist,c.distcode,0,c.work,B);c.distbits=B.bits;if(R){u.msg="invalid distances set";c.mode=30;break}c.mode=20;if(6===D)break a;case 20:c.mode=21;case 21:if(6<=m&&258<=a){u.next_out=P;u.avail_out=a;u.next_in=e;u.avail_in=m;c.hold=g;c.bits=q;p(u,E);P=u.next_out;F=u.output;a=u.avail_out;e=u.next_in;b=u.input;m=u.avail_in;g=c.hold;q=c.bits;12===c.mode&&(c.back=-1);break}for(c.back=0;;){d=c.lencode[g&(1<<c.lenbits)-1];B=d>>>24;H=d>>>16&255;d&=65535;if(B<=q)break;if(0===m)break a;m--;
g+=b[e++]<<q;q+=8}if(H&&0===(H&240)){var z=B;var C=H;for(L=d;;){d=c.lencode[L+((g&(1<<z+C)-1)>>z)];B=d>>>24;H=d>>>16&255;d&=65535;if(z+B<=q)break;if(0===m)break a;m--;g+=b[e++]<<q;q+=8}g>>>=z;q-=z;c.back+=z}g>>>=B;q-=B;c.back+=B;c.length=d;if(0===H){c.mode=26;break}if(H&32){c.back=-1;c.mode=12;break}if(H&64){u.msg="invalid literal/length code";c.mode=30;break}c.extra=H&15;c.mode=22;case 22:if(c.extra){for(H=c.extra;q<H;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}c.length+=g&(1<<c.extra)-1;g>>>=c.extra;
q-=c.extra;c.back+=c.extra}c.was=c.length;c.mode=23;case 23:for(;;){d=c.distcode[g&(1<<c.distbits)-1];B=d>>>24;H=d>>>16&255;d&=65535;if(B<=q)break;if(0===m)break a;m--;g+=b[e++]<<q;q+=8}if(0===(H&240)){z=B;C=H;for(L=d;;){d=c.distcode[L+((g&(1<<z+C)-1)>>z)];B=d>>>24;H=d>>>16&255;d&=65535;if(z+B<=q)break;if(0===m)break a;m--;g+=b[e++]<<q;q+=8}g>>>=z;q-=z;c.back+=z}g>>>=B;q-=B;c.back+=B;if(H&64){u.msg="invalid distance code";c.mode=30;break}c.offset=d;c.extra=H&15;c.mode=24;case 24:if(c.extra){for(H=
c.extra;q<H;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}c.offset+=g&(1<<c.extra)-1;g>>>=c.extra;q-=c.extra;c.back+=c.extra}if(c.offset>c.dmax){u.msg="invalid distance too far back";c.mode=30;break}c.mode=25;case 25:if(0===a)break a;B=E-a;if(c.offset>B){B=c.offset-B;if(B>c.whave&&c.sane){u.msg="invalid distance too far back";c.mode=30;break}B>c.wnext?(B-=c.wnext,H=c.wsize-B):H=c.wnext-B;B>c.length&&(B=c.length);z=c.window}else z=F,H=P-c.offset,B=c.length;B>a&&(B=a);a-=B;c.length-=B;do F[P++]=z[H++];while(--B);
0===c.length&&(c.mode=21);break;case 26:if(0===a)break a;F[P++]=c.length;a--;c.mode=21;break;case 27:if(c.wrap){for(;32>q;){if(0===m)break a;m--;g|=b[e++]<<q;q+=8}E-=a;u.total_out+=E;c.total+=E;E&&(u.adler=c.check=c.flags?l(c.check,F,E,P-E):k(c.check,F,E,P-E));E=a;if((c.flags?g:x(g))!==c.check){u.msg="incorrect data check";c.mode=30;break}q=g=0}c.mode=28;case 28:if(c.wrap&&c.flags){for(;32>q;){if(0===m)break a;m--;g+=b[e++]<<q;q+=8}if(g!==(c.total&4294967295)){u.msg="incorrect length check";c.mode=
30;break}q=g=0}c.mode=29;case 29:R=1;break a;case 30:R=-3;break a;case 31:return-4;default:return-2}u.next_out=P;u.avail_out=a;u.next_in=e;u.avail_in=m;c.hold=g;c.bits=q;if(c.wsize||E!==u.avail_out&&30>c.mode&&(27>c.mode||4!==D))b=u.output,e=u.next_out,P=E-u.avail_out,a=u.state,null===a.window&&(a.wsize=1<<a.wbits,a.wnext=0,a.whave=0,a.window=new t.Buf8(a.wsize)),P>=a.wsize?(t.arraySet(a.window,b,e-a.wsize,a.wsize,0),a.wnext=0,a.whave=a.wsize):(m=a.wsize-a.wnext,m>P&&(m=P),t.arraySet(a.window,b,e-
P,m,a.wnext),(P-=m)?(t.arraySet(a.window,b,e-P,P,0),a.wnext=P,a.whave=a.wsize):(a.wnext+=m,a.wnext===a.wsize&&(a.wnext=0),a.whave<a.wsize&&(a.whave+=m)));S-=u.avail_in;E-=u.avail_out;u.total_in+=S;u.total_out+=E;c.total+=E;c.wrap&&E&&(u.adler=c.check=c.flags?l(c.check,F,E,u.next_out-E):k(c.check,F,E,u.next_out-E));u.data_type=c.bits+(c.last?64:0)+(12===c.mode?128:0)+(20===c.mode||15===c.mode?256:0);(0===S&&0===E||4===D)&&0===R&&(R=-5);return R};y.inflateEnd=function(u){if(!u||!u.state)return-2;var D=
u.state;D.window&&(D.window=null);u.state=null;return 0};y.inflateGetHeader=function(u,D){if(!u||!u.state)return-2;u=u.state;if(0===(u.wrap&2))return-2;u.head=D;D.done=!1;return 0};y.inflateInfo="pako inflate (from Nodeca project)"},{"../utils/common":27,"./adler32":29,"./crc32":31,"./inffast":34,"./inftrees":36}],36:[function(v,J,y){var x=v("../utils/common"),r=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],h=[16,16,16,16,16,16,16,16,17,17,17,17,18,18,
18,18,19,19,19,19,20,20,20,20,21,21,21,21,16,72,78],A=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577,0,0],w=[16,16,16,16,17,17,18,18,19,19,20,20,21,21,22,22,23,23,24,24,25,25,26,26,27,27,28,28,29,29,64,64];J.exports=function(f,t,k,l,p,n,G,O){var T=O.bits,u,D,L,N,W,c,P=0,F=new x.Buf16(16);var a=new x.Buf16(16);var e,b=0;for(u=0;15>=u;u++)F[u]=0;for(D=0;D<l;D++)F[t[k+D]]++;var m=T;for(L=15;1<=L&&0===F[L];L--);m>L&&(m=L);if(0===L)return p[n++]=
20971520,p[n++]=20971520,O.bits=1,0;for(T=1;T<L&&0===F[T];T++);m<T&&(m=T);for(u=N=1;15>=u;u++)if(N<<=1,N-=F[u],0>N)return-1;if(0<N&&(0===f||1!==L))return-1;a[1]=0;for(u=1;15>u;u++)a[u+1]=a[u]+F[u];for(D=0;D<l;D++)0!==t[k+D]&&(G[a[t[k+D]]++]=D);if(0===f){var g=e=G;var q=19}else 1===f?(g=r,P-=257,e=h,b-=257,q=256):(g=A,e=w,q=-1);D=W=0;u=T;var S=n;l=m;a=0;var E=-1;var R=1<<m;var H=R-1;if(1===f&&852<R||2===f&&592<R)return 1;for(var B=0;;){B++;var d=u-a;if(G[D]<q){var z=0;var C=G[D]}else G[D]>q?(z=e[b+
G[D]],C=g[P+G[D]]):(z=96,C=0);N=1<<u-a;T=c=1<<l;do c-=N,p[S+(W>>a)+c]=d<<24|z<<16|C|0;while(0!==c);for(N=1<<u-1;W&N;)N>>=1;0!==N?(W&=N-1,W+=N):W=0;D++;if(0===--F[u]){if(u===L)break;u=t[k+G[D]]}if(u>m&&(W&H)!==E){0===a&&(a=m);S+=T;l=u-a;for(N=1<<l;l+a<L;){N-=F[l+a];if(0>=N)break;l++;N<<=1}R+=1<<l;if(1===f&&852<R||2===f&&592<R)return 1;E=W&H;p[E]=m<<24|l<<16|S-n|0}}0!==W&&(p[S+W]=u-a<<24|4194304);O.bits=m;return 0}},{"../utils/common":27}],37:[function(v,J,y){J.exports={2:"need dictionary",1:"stream end",
0:"","-1":"file error","-2":"stream error","-3":"data error","-4":"insufficient memory","-5":"buffer error","-6":"incompatible version"}},{}],38:[function(v,J,y){function x(d){for(var z=d.length;0<=--z;)d[z]=0}function r(d,z){d.pending_buf[d.pending++]=z&255;d.pending_buf[d.pending++]=z>>>8&255}function h(d,z,C){d.bi_valid>16-C?(d.bi_buf|=z<<d.bi_valid&65535,r(d,d.bi_buf),d.bi_buf=z>>16-d.bi_valid,d.bi_valid+=C-16):(d.bi_buf|=z<<d.bi_valid&65535,d.bi_valid+=C)}function A(d,z,C){h(d,C[2*z],C[2*z+1])}
function w(d,z){var C=0;do C|=d&1,d>>>=1,C<<=1;while(0<--z);return C>>>1}function f(d,z,C){var I=Array(16),M=0,Q;for(Q=1;15>=Q;Q++)I[Q]=M=M+C[Q-1]<<1;for(C=0;C<=z;C++)M=d[2*C+1],0!==M&&(d[2*C]=w(I[M]++,M))}function t(d){var z;for(z=0;286>z;z++)d.dyn_ltree[2*z]=0;for(z=0;30>z;z++)d.dyn_dtree[2*z]=0;for(z=0;19>z;z++)d.bl_tree[2*z]=0;d.dyn_ltree[512]=1;d.opt_len=d.static_len=0;d.last_lit=d.matches=0}function k(d){8<d.bi_valid?r(d,d.bi_buf):0<d.bi_valid&&(d.pending_buf[d.pending++]=d.bi_buf);d.bi_buf=
0;d.bi_valid=0}function l(d,z,C,I){var M=2*z,Q=2*C;return d[M]<d[Q]||d[M]===d[Q]&&I[z]<=I[C]}function p(d,z,C){for(var I=d.heap[C],M=C<<1;M<=d.heap_len;){M<d.heap_len&&l(z,d.heap[M+1],d.heap[M],d.depth)&&M++;if(l(z,I,d.heap[M],d.depth))break;d.heap[C]=d.heap[M];C=M;M<<=1}d.heap[C]=I}function n(d,z,C){var I=0;if(0!==d.last_lit){do{var M=d.pending_buf[d.d_buf+2*I]<<8|d.pending_buf[d.d_buf+2*I+1];var Q=d.pending_buf[d.l_buf+I];I++;if(0===M)A(d,Q,z);else{var K=b[Q];A(d,K+256+1,z);var V=N[K];0!==V&&(Q-=
m[K],h(d,Q,V));M--;K=256>M?e[M]:e[256+(M>>>7)];A(d,K,C);V=W[K];0!==V&&(M-=g[K],h(d,M,V))}}while(I<d.last_lit)}A(d,256,z)}function G(d,z){var C=z.dyn_tree,I=z.stat_desc.static_tree,M=z.stat_desc.has_stree,Q=z.stat_desc.elems,K,V=-1;d.heap_len=0;d.heap_max=573;for(K=0;K<Q;K++)0!==C[2*K]?(d.heap[++d.heap_len]=V=K,d.depth[K]=0):C[2*K+1]=0;for(;2>d.heap_len;){var U=d.heap[++d.heap_len]=2>V?++V:0;C[2*U]=1;d.depth[U]=0;d.opt_len--;M&&(d.static_len-=I[2*U+1])}z.max_code=V;for(K=d.heap_len>>1;1<=K;K--)p(d,
C,K);U=Q;do K=d.heap[1],d.heap[1]=d.heap[d.heap_len--],p(d,C,1),I=d.heap[1],d.heap[--d.heap_max]=K,d.heap[--d.heap_max]=I,C[2*U]=C[2*K]+C[2*I],d.depth[U]=(d.depth[K]>=d.depth[I]?d.depth[K]:d.depth[I])+1,C[2*K+1]=C[2*I+1]=U,d.heap[1]=U++,p(d,C,1);while(2<=d.heap_len);d.heap[--d.heap_max]=d.heap[1];K=z.dyn_tree;U=z.max_code;I=z.stat_desc.static_tree;M=z.stat_desc.has_stree;Q=z.stat_desc.extra_bits;var Y=z.stat_desc.extra_base,aa=z.stat_desc.max_length,X,ba=0;for(X=0;15>=X;X++)d.bl_count[X]=0;K[2*d.heap[d.heap_max]+
1]=0;for(z=d.heap_max+1;573>z;z++){var Z=d.heap[z];X=K[2*K[2*Z+1]+1]+1;X>aa&&(X=aa,ba++);K[2*Z+1]=X;if(!(Z>U)){d.bl_count[X]++;var da=0;Z>=Y&&(da=Q[Z-Y]);var ea=K[2*Z];d.opt_len+=ea*(X+da);M&&(d.static_len+=ea*(I[2*Z+1]+da))}}if(0!==ba){do{for(X=aa-1;0===d.bl_count[X];)X--;d.bl_count[X]--;d.bl_count[X+1]+=2;d.bl_count[aa]--;ba-=2}while(0<ba);for(X=aa;0!==X;X--)for(Z=d.bl_count[X];0!==Z;)I=d.heap[--z],I>U||(K[2*I+1]!==X&&(d.opt_len+=(X-K[2*I+1])*K[2*I],K[2*I+1]=X),Z--)}f(C,V,d.bl_count)}function O(d,
z,C){var I,M=-1,Q=z[1],K=0,V=7,U=4;0===Q&&(V=138,U=3);z[2*(C+1)+1]=65535;for(I=0;I<=C;I++){var Y=Q;Q=z[2*(I+1)+1];++K<V&&Y===Q||(K<U?d.bl_tree[2*Y]+=K:0!==Y?(Y!==M&&d.bl_tree[2*Y]++,d.bl_tree[32]++):10>=K?d.bl_tree[34]++:d.bl_tree[36]++,K=0,M=Y,0===Q?(V=138,U=3):Y===Q?(V=6,U=3):(V=7,U=4))}}function T(d,z,C){var I,M=-1,Q=z[1],K=0,V=7,U=4;0===Q&&(V=138,U=3);for(I=0;I<=C;I++){var Y=Q;Q=z[2*(I+1)+1];if(!(++K<V&&Y===Q)){if(K<U){do A(d,Y,d.bl_tree);while(0!==--K)}else 0!==Y?(Y!==M&&(A(d,Y,d.bl_tree),K--),
A(d,16,d.bl_tree),h(d,K-3,2)):10>=K?(A(d,17,d.bl_tree),h(d,K-3,3)):(A(d,18,d.bl_tree),h(d,K-11,7));K=0;M=Y;0===Q?(V=138,U=3):Y===Q?(V=6,U=3):(V=7,U=4)}}}function u(d){var z=4093624447,C;for(C=0;31>=C;C++,z>>>=1)if(z&1&&0!==d.dyn_ltree[2*C])return 0;if(0!==d.dyn_ltree[18]||0!==d.dyn_ltree[20]||0!==d.dyn_ltree[26])return 1;for(C=32;256>C;C++)if(0!==d.dyn_ltree[2*C])return 1;return 0}function D(d,z,C,I){h(d,I?1:0,3);k(d);r(d,C);r(d,~C);L.arraySet(d.pending_buf,d.window,z,C,d.pending);d.pending+=C}var L=
v("../utils/common"),N=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0],W=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],c=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,3,7],P=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],F=Array(576);x(F);var a=Array(60);x(a);var e=Array(512);x(e);var b=Array(256);x(b);var m=Array(29);x(m);var g=Array(30);x(g);var q=function(d,z,C,I,M){this.static_tree=d;this.extra_bits=z;this.extra_base=C;this.elems=I;this.max_length=M;this.has_stree=d&&
d.length},S,E,R,H=function(d,z){this.dyn_tree=d;this.max_code=0;this.stat_desc=z},B=!1;y._tr_init=function(d){if(!B){var z,C,I,M=Array(16);for(I=C=0;28>I;I++)for(m[I]=C,z=0;z<1<<N[I];z++)b[C++]=I;b[C-1]=I;for(I=C=0;16>I;I++)for(g[I]=C,z=0;z<1<<W[I];z++)e[C++]=I;for(C>>=7;30>I;I++)for(g[I]=C<<7,z=0;z<1<<W[I]-7;z++)e[256+C++]=I;for(z=0;15>=z;z++)M[z]=0;for(z=0;143>=z;)F[2*z+1]=8,z++,M[8]++;for(;255>=z;)F[2*z+1]=9,z++,M[9]++;for(;279>=z;)F[2*z+1]=7,z++,M[7]++;for(;287>=z;)F[2*z+1]=8,z++,M[8]++;f(F,287,
M);for(z=0;30>z;z++)a[2*z+1]=5,a[2*z]=w(z,5);S=new q(F,N,257,286,15);E=new q(a,W,0,30,15);R=new q([],c,0,19,7);B=!0}d.l_desc=new H(d.dyn_ltree,S);d.d_desc=new H(d.dyn_dtree,E);d.bl_desc=new H(d.bl_tree,R);d.bi_buf=0;d.bi_valid=0;t(d)};y._tr_stored_block=D;y._tr_flush_block=function(d,z,C,I){var M=0;if(0<d.level){2===d.strm.data_type&&(d.strm.data_type=u(d));G(d,d.l_desc);G(d,d.d_desc);O(d,d.dyn_ltree,d.l_desc.max_code);O(d,d.dyn_dtree,d.d_desc.max_code);G(d,d.bl_desc);for(M=18;3<=M&&0===d.bl_tree[2*
P[M]+1];M--);d.opt_len+=3*(M+1)+14;var Q=d.opt_len+3+7>>>3;var K=d.static_len+3+7>>>3;K<=Q&&(Q=K)}else Q=K=C+5;if(C+4<=Q&&-1!==z)D(d,z,C,I);else if(4===d.strategy||K===Q)h(d,2+(I?1:0),3),n(d,F,a);else{h(d,4+(I?1:0),3);z=d.l_desc.max_code+1;C=d.d_desc.max_code+1;M+=1;h(d,z-257,5);h(d,C-1,5);h(d,M-4,4);for(Q=0;Q<M;Q++)h(d,d.bl_tree[2*P[Q]+1],3);T(d,d.dyn_ltree,z-1);T(d,d.dyn_dtree,C-1);n(d,d.dyn_ltree,d.dyn_dtree)}t(d);I&&k(d)};y._tr_tally=function(d,z,C){d.pending_buf[d.d_buf+2*d.last_lit]=z>>>8&255;
d.pending_buf[d.d_buf+2*d.last_lit+1]=z&255;d.pending_buf[d.l_buf+d.last_lit]=C&255;d.last_lit++;0===z?d.dyn_ltree[2*C]++:(d.matches++,z--,d.dyn_ltree[2*(b[C]+256+1)]++,d.dyn_dtree[2*(256>z?e[z]:e[256+(z>>>7)])]++);return d.last_lit===d.lit_bufsize-1};y._tr_align=function(d){h(d,2,3);A(d,256,F);16===d.bi_valid?(r(d,d.bi_buf),d.bi_buf=0,d.bi_valid=0):8<=d.bi_valid&&(d.pending_buf[d.pending++]=d.bi_buf&255,d.bi_buf>>=8,d.bi_valid-=8)}},{"../utils/common":27}],39:[function(v,J,y){J.exports=function(){this.input=
null;this.total_in=this.avail_in=this.next_in=0;this.output=null;this.total_out=this.avail_out=this.next_out=0;this.msg="";this.state=null;this.data_type=2;this.adler=0}},{}]},{},[9])(9)});
