var HogPdh=function(){function h(a,b){var c=p(a);c=[{id:440786851,data:[{data:1,id:17030},{data:1,id:17143},{data:4,id:17138},{data:8,id:17139},{data:"webm",id:17026},{data:2,id:17031},{data:2,id:17029}]},{id:408125543,data:[{id:357149030,data:[{data:1E6,id:2807729},{data:"whammy",id:19840},{data:"whammy",id:22337},{data:y(c.duration),id:17545}]},{id:374648427,data:[{id:174,data:[{data:1,id:215},{data:1,id:29637},{data:0,id:156},{data:"und",id:2274716},{data:"V_VP8",id:134},{data:"VP8",id:2459272},
{data:1,id:131},{id:224,data:[{data:c.width,id:176},{data:c.height,id:186}]}]}]},{id:475249515,data:[]}]}];for(var f=c[1],d=f.data[2],e=0,g=0;e<a.length;){d.data.push({id:187,data:[{data:Math.round(g),id:179},{id:183,data:[{data:1,id:247},{data:0,size:8,id:241}]}]});var k=[],l=0;do k.push(a[e]),l+=a[e].duration,e++;while(e<a.length&&3E4>l);var m=0;k={id:524531317,data:[{data:Math.round(g),id:231}].concat(k.map(function(t){var A=z({discardable:0,frame:t.data.slice(4),invisible:0,keyframe:1,lacing:0,
trackNum:1,timecode:Math.round(m)});m+=t.duration;return{data:A,id:163}}))};f.data.push(k);g+=l}for(e=a=0;e<f.data.length;e++)3<=e&&(d.data[e-3].data[1].data[1].data=a),g=q([f.data[e]],b),a+=g.size||g.byteLength||g.length,2!=e&&(f.data[e]=g);return q(c,b)}function p(a){for(var b=a[0].width,c=a[0].height,f=a[0].duration,d=1;d<a.length;d++){if(a[d].width!=b)throw"Frame "+(d+1)+" has a different width";if(a[d].height!=c)throw"Frame "+(d+1)+" has a different height";if(0>a[d].duration||32767<a[d].duration)throw"Frame "+
(d+1)+" has a weird duration (must be between 0 and 32767)";f+=a[d].duration}return{duration:f,width:b,height:c}}function u(a){var b=[];a=(a.length%8?Array(9-a.length%8).join("0"):"")+a;for(var c=0;c<a.length;c+=8)b.push(parseInt(a.substr(c,8),2));return new Uint8Array(b)}function q(a,b){for(var c=[],f=0;f<a.length;f++)if("id"in a[f]){var d=a[f].data;"object"==typeof d&&(d=q(d,b));if("number"==typeof d)if("size"in a[f]){var e=a[f].size,g=new Uint8Array(e);for(--e;0<=e;e--)g[e]=d&255,d>>=8;d=g}else d=
u(d.toString(2));if("string"==typeof d){g=new Uint8Array(d.length);for(e=0;e<d.length;e++)g[e]=d.charCodeAt(e);d=g}e=d.size||d.byteLength||d.length;g=Math.ceil(Math.ceil(Math.log(e)/Math.log(2))/8);e=e.toString(2);e=Array(7*g+8-e.length).join("0")+e;g=Array(g).join("0")+"1"+e;e=c;var k=e.push;var l=a[f].id;for(var m=[];0<l;)m.push(l&255),l>>=8;l=new Uint8Array(m.reverse());k.call(e,l);c.push(u(g));c.push(d)}else c.push(a[f]);return b?(a=v(c),new Uint8Array(a)):new Blob(c,{type:"video/webm"})}function v(a,
b){null==b&&(b=[]);for(var c=0;c<a.length;c++)"object"==typeof a[c]?v(a[c],b):b.push(a[c]);return b}function z(a){var b=0;a.keyframe&&(b|=128);a.invisible&&(b|=8);a.lacing&&(b|=a.lacing<<1);a.discardable&&(b|=1);if(127<a.trackNum)throw"TrackNumber > 127 not supported";return[a.trackNum|128,a.timecode>>8,a.timecode&255,b].map(function(c){return String.fromCharCode(c)}).join("")+a.frame}function w(a){for(var b=a.RIFF[0].WEBP[0],c=b.indexOf("\u009d\u0001*"),f=0,d=[];4>f;f++)d[f]=b.charCodeAt(c+3+f);
f=d[1]<<8|d[0];c=f&16383;f=d[3]<<8|d[2];return{width:c,height:f&16383,data:b,riff:a}}function x(a,b){return parseInt(a.substr(b,4).split("").map(function(c){c=c.charCodeAt(0).toString(2);return Array(8-c.length+1).join("0")+c}).reverse().join(""),2)}function r(a){for(var b=0,c={};b<a.length;){var f=a.substr(b,4);c[f]=c[f]||[];if("RIFF"==f||"LIST"==f){var d=x(a,b+4),e=a.substr(b+4+4,d);b+=8+d;c[f].push(r(e))}else{if("WEBP"==f)switch(d=a.substr(b+4,4),d){case "VP8X":f=c[f];d=f.push;a:{b=a.substr(b+
8);for(e=14;e<b.length;){var g=b.substr(e,4);e+=4;let k=x(b,e);e+=4;switch(g){case "VP8 ":case "VP8L":g=b.substr(e-4,4);b=b.substr(e,k);b=g+b;break a;default:e+=k}}console.error("VP8X format error: missing VP8/VP8L chunk.");b=void 0}d.call(f,b);break;case "VP8 ":case "VP8L":c[f].push(a.substr(b+8));break;default:console.error(`not supported webp version: \"${d}\"`)}else c[f].push(a.substr(b+4));b=a.length}}return c}function y(a){return[].slice.call(new Uint8Array((new Float64Array([a])).buffer),0).map(function(b){return String.fromCharCode(b)}).reverse().join("")}
function n(a,b){this.frames=[];this.duration=1E3/a;this.quality=b||.8}n.prototype.add=function(a,b){if("undefined"!=typeof b&&this.duration)throw"you can't pass a duration if the fps is set";if("undefined"==typeof b&&!this.duration)throw"if you don't have the fps set, you need to have durations here.";a.canvas&&(a=a.canvas);if(a.toDataURL)a=a.getContext("2d").getImageData(0,0,a.width,a.height);else if("string"!=typeof a)throw"frame must be a a HTMLCanvasElement, a CanvasRenderingContext2D or a DataURI formatted string";
if("string"===typeof a&&!/^data:image\/webp;base64,/ig.test(a))throw"Input must be formatted properly as a base64 encoded DataURI of type image/webp";this.frames.push({image:a,duration:b||this.duration})};n.prototype.encodeFrames=function(a){if(this.frames[0].image instanceof ImageData){var b=this.frames,c=document.createElement("canvas"),f=c.getContext("2d");c.width=this.frames[0].image.width;c.height=this.frames[0].image.height;var d=function(e){console.log("encodeFrame",e);var g=b[e];f.putImageData(g.image,
0,0);g.image=c.toDataURL("image/webp",this.quality);e<b.length-1?setTimeout(function(){d(e+1)},1):a()}.bind(this);d(0)}else a()};n.prototype.compile=function(a,b){this.encodeFrames(function(){var c=new h(this.frames.map(function(f){var d=w(r(atob(f.image.slice(23))));d.duration=f.duration;return d}),a);b(c)}.bind(this))};return{Video:n,fromImageArray:function(a,b,c){return h(a.map(function(f){f=w(r(atob(f.slice(23))));f.duration=1E3/b;return f}),c)},toWebM:h}}(),percent=0,frameCnt=0,delaySum=0,encoder=
new HogPdh.Video;onmessage=function(h){h=h.data;"frameAdd"===h.cmd?(encoder.add(h.imgData,h.delay),postMessage({cmd:"percent",percent:++percent})):"finish"===h.cmd&&encoder.compile(!1,function(p){postMessage({cmd:"finish",output:p})})};
